### ISSUE TITLE
UX issue with events page

### ISSUE THREAD

**Issue by Njong392** [EddieHubCommunity/LinkFree#7188] opened 2023-05-26 08:46 UTC
### Description

When I go to the events page, and click on an event category for example, say "All future events", at first I notice nothing happening. If I'm a first time user, there is no way to know that i need to scroll to the bottom of the page to actually see the events from the category I have clicked on. I clicked multiple times, thought nothing was happening, and that it was a bug. Just happened to scroll down for a sec before realising that the events are displayed below.

A possible solution would be to automatically scroll down to the section where events are displayed, when a user clicks on an event category for example. But maybe there could be a better way to address this?

### Screenshots

![screen record of Amanda Martin's profile, reproducing error described above](https://github.com/EddieHubCommunity/LinkFree/assets/81039882/85909b92-de4b-4e2f-8c99-666109d6d9b0)

**Comment by SaraJaoude** [comment] 2023-05-26 09:33
Thanks for your suggestion @Njong392 but this would be a duplicate of the already existing Issue #5393 so I will close this.

**Closed by SaraJaoude** 2023-05-26 09:33 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
