### ISSUE TITLE
[Color issue ] <on the playground tab in light mode>

### ISSUE THREAD

**Issue by ManashAnand** [EddieHubCommunity/LinkFree#8186] opened 2023-07-14 10:48 UTC
### Description

![linkfree p1 2](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/2dee1a21-15b9-42bd-8fb7-d536b82542ee)
As we can see in the dark mode we can visualize the button pretty easily but in the light mode
![linkfree p1 1](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/1d6a2dd4-e424-4ac1-bb3a-421b0976b2ad)
It is not visible quiet enough although on hover we can see the button but this is not a great UX as I think,

We should use a little border and light color to demostrate the button and then on hover we can give the effect

### Additional information

It's my first issue raised on this project.
Feel free to correct me at any step and 
Thanks for giving the time .

**Comment by eddiejaoude** [comment] 2023-07-16 19:34
Good idea 👍 it can be added to the button component

**Comment by ManashAnand** [comment] 2023-07-16 19:37
thank you very much,
I would like to work on this issue 
plz assign it to me.

**Comment by SaraJaoude** [comment] 2023-07-17 08:05
> thank you very much,
> I would like to work on this issue
> plz assign it to me.

@ManashAnand I have assigned it to you.

**Comment by eddiejaoude** [comment] 2023-07-17 21:40
It looks good, how do the buttons look in other places on the site? I think it would be best for you to create the pull request and we can have a look/play with the changes

**Comment by Satyam-G5** [comment] 2023-08-01 20:33
If the issue is still open i would like to work on this .

**Comment by SaraJaoude** [comment] 2023-08-02 11:48
> If the issue is still open i would like to work on this .

@Satyam-G5 I have assigned this to you

**Comment by ManashAnand** [comment] 2023-08-02 12:05
I have added this pull request in my repo maybe 
and thought that it was added to the main webapp

I don't exactly know the steps 
Can you elaborate it please 
![mpl](https://github.com/EddieHubCommunity/LinkFree/assets/91553087/74796c5d-6261-4789-8006-fd37812af235)

**Comment by SaraJaoude** [comment] 2023-08-03 07:14
@ManashAnand thank you for trying to complete this but this has now been assigned to someone else. In future if you are having any difficulties please add a comment in the issue.

**Closed** 2023-08-08 21:06 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, good first issue, 🔢 points: 2
