### ISSUE TITLE
[FEATURE] Tab for Projects

### ISSUE THREAD

**Issue by LinuxGamer** [EddieHubCommunity/LinkFree#2892] opened 2023-01-08 18:58 UTC
### Description

A tab on user pages for projects, such as their favourite, ones their working on at the moment, ones that they are proud of. The ability to have repo links, screenshots and hosted links as well as a description about the projects,

**Comment by ThorOnTheRocks** [comment] 2023-01-10 22:53
@LinuxGamer That sounds like an awesome idea! Would love to discuss more regarding the UI implementation of this feature! Are you already working on this? Let me know if this issue is still waiting for confirmation or if you would like to exchange ideas!

**Comment by LinuxGamer** [comment] 2023-01-11 09:43
I am not working on this. I am not sure whether the maintainers are ok with this being added yet tho.

**Comment by eddiejaoude** [comment] 2023-01-12 09:15
Yes great idea 👍 this issue is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2835 so I will close it, we can continue the conversation over there

**Closed by eddiejaoude** 2023-01-12 09:15 UTC
Labels: ⭐ goal: addition
