### ISSUE TITLE
[BUG] Testimonials shows zero if no testimonial exist for user 

### ISSUE THREAD

**Issue by raviraj-github** [EddieHubCommunity/LinkFree#8235] opened 2023-07-17 19:08 UTC
### Description

**Instructions for Reproduction:**
1. Begin by logging in to Linkfree.
2. Access the "Account" section and navigate to the testimonials tab.
3. In case you do not have any testimonials, the following message will be displayed.

This issue can be replicated in both the local and production environments.

**Suggested Fix**
_File name: /pages/account/manage/testimonials.js_ 

**I think istead of checking like this :** 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/3a3fe5ac-9e79-49a2-b220-b1bbb4b80115)

**Use conditional operator like this:** 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/82043ccc-e27f-4afd-86d5-de90da463aa9)

Hopefully this will solve the issue.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/11041028/3e4a1f45-9ba1-4696-8523-1bbce4d861a1)

**Comment by raviraj-github** [comment] 2023-07-19 14:27
> Able to recreate, will unlock. Did you want to work on this issue?

I can work on this. No issue. Just wanted to inform you, I was working on one issue, for that I have already raised PR and waiting for that PR to be merged. So if I am not breaking the "**one issue at a time**" rule then feel free to assign it to me.

**Comment by amandamartin-dev** [comment] 2023-07-19 14:28
> I can work on this. No issue. Just wanted to inform you, I was working on one issue, for that I have already raised PR and waiting for that PR to be merged. So if I am not breaking the "one issue at a time" rule then feel free to assign it to me

Ah! Thank you so much for your honesty! I forgot to check that first.  Lets leave it open for someone else for now and if no one takes it by the time your PR is all merged, let us know

**Comment by tanbirali** [comment] 2023-07-19 15:17
If @raviraj-github doesn't mind can I take this?

**Comment by sumitunique777** [comment] 2023-07-20 17:18
Can I take up this issue?

**Comment by adarshmalviya12** [comment] 2023-07-21 14:09
If the issue is still unassigned and no one is actively working on it, Please let me know if the issue is available for me to work on, I can work on it

**Comment by vishalsingh2972** [comment] 2023-07-21 15:01
can I work on this if the issue is still open?

**Comment by eddiejaoude** [comment] 2023-07-22 08:14
@tanbirali as you asked first I have assigned it to you

sorry @raviraj-github I am behind in github notifications

**Closed** 2023-08-10 16:16 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 2
