### ISSUE TITLE
Nested main tags

### ISSUE THREAD

**Issue by EmmaDawsonDev** [EddieHubCommunity/LinkFree#4224] opened 2023-01-29 15:49 UTC
### Description

On the landing page there are two main tags one nested inside the other when there should only be one.

### Screenshots

<img width="115" alt="Screenshot_20230129_164626" src="https://user-images.githubusercontent.com/57045550/215338132-334f9341-5b64-4af0-b1c4-376755de9339.png">

**Comment by codewithbharat** [comment] 2023-01-29 17:23
@EmmaDawsonDev I would like to work on this issue.... please assign it to me.

**Comment by EmmaDawsonDev** [comment] 2023-01-29 17:35
Sure!

**Comment by codewithbharat** [comment] 2023-01-29 17:44
@EmmaDawsonDev can please help me with setting up development environment for this repo

**Comment by EmmaDawsonDev** [comment] 2023-01-29 18:01
Which stage are you stuck on?

**Comment by codewithbharat** [comment] 2023-01-29 18:28
@EmmaDawsonDev creating `.env` file

**Comment by EmmaDawsonDev** [comment] 2023-01-29 18:48
Create a file called .env and there is a .env.example file which you can copy the contents and paste into the .env file.

**Comment by codewithbharat** [comment] 2023-01-29 18:58
NEXT_PUBLIC_GA_MEASUREMENT_ID=""
SHADOWBAN=""

can you explain these...

**Comment by EmmaDawsonDev** [comment] 2023-01-29 19:09
You shouldn’t need to change those. They are used in production for analytics and banning people that game the system

**Comment by codewithbharat** [comment] 2023-01-29 19:31
@EmmaDawsonDev 
![image](https://user-images.githubusercontent.com/72380658/215351179-f32f9298-9ee2-4c5a-91f3-872bda0bd66c.png)

**Comment by codewithbharat** [comment] 2023-01-29 19:32
@EmmaDawsonDev browser get's blank and db connection fails in github codespaces

**Comment by codewithbharat** [comment] 2023-01-29 19:34
@EmmaDawsonDev by the way I have already created a pull request have a look

**Comment by alokVerma749** [comment] 2023-01-30 03:52
can i work on this issue

**Comment by codewithbharat** [comment] 2023-01-30 03:54
@alokVerma749 I'm already on it

**Comment by GauravBurande** [comment] 2023-01-30 15:06
@alokVerma749 be patient, you'll get an issue to work on.

@codewithbharat is already working on this issue.

**Comment by alokVerma749** [comment] 2023-01-30 15:08
fine

**Comment by eddiejaoude** [comment] 2023-02-05 04:13
Sorry @codewithbharat I merged in another Pull Request without checking the issue was already assigned to you

Here is the pull request https://github.com/EddieHubCommunity/LinkFree/pull/4317

@alokVerma749 please check the issue is not assigned **before** making any changes and raising a pull request - as this causes confusion and creates more work for everyone

**Closed by eddiejaoude** 2023-02-05 04:13 UTC
Labels: 🛠 goal: fix, good first issue
