### ISSUE TITLE
[OTHER] "no milestones found" card is misaligned 

### ISSUE THREAD

**Issue by firasRoggai** [EddieHubCommunity/LinkFree#8374] opened 2023-07-28 01:52 UTC
### Description

the card needs a small space so it doesn't look crammed
![image](https://github.com/EddieHubCommunity/LinkFree/assets/96572225/573bf7d1-ef3b-470e-9b59-456715f8e281)

should be : 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/96572225/e3acc09a-8915-4979-97c8-e31259343045)

### Additional information

would like to fix this one

**Comment by SaraJaoude** [comment] 2023-07-28 10:34
Thank you, but I will close this Issue as it is a duplicate of: https://github.com/EddieHubCommunity/LinkFree/issues/8210

**Closed by SaraJaoude** 2023-07-28 10:34 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
