### ISSUE TITLE
Two Javascript tags in "Search page" 

### ISSUE THREAD

**Issue by geeky-sambhav** [EddieHubCommunity/LinkFree#6312] opened 2023-04-23 15:36 UTC
### Description

On the search page, there are two Javascript tags one is Javascript and another is JavaScript.Since they both have same meaning there should be only 1 Javascript tag comprising of both.I am attaching the screenshot for reference

### Screenshots

Before/Now: 
![issue](https://user-images.githubusercontent.com/83087385/233848952-6e3cdfd8-04a6-42ac-a61c-7bc2816df644.png)

After Correcting the issue it should be like this: 
![issue-solved](https://user-images.githubusercontent.com/83087385/233849082-803d8d61-78d6-4069-8512-2ecd35bd0ecb.png)

### Additional information

For more clarification u can ask me personally on discord
![discord](https://user-images.githubusercontent.com/83087385/233849285-4fa8178c-e542-482e-b9a5-b45ba08243f7.png)

**Comment by amandamartin-dev** [comment] 2023-04-26 21:39
This issue is a duplicate of #4676 will close.  Please remember to search for open issues before creating a new one. Thanks!

**Closed by amandamartin-dev** 2023-04-26 21:39 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
