### ISSUE TITLE
Theme Option

### ISSUE THREAD

**Issue by dunyanong** [EddieHubCommunity/LinkFree#1371] opened 2022-06-10 10:06 UTC
### Description

It would be a great idea to have a dark theme option for the website because some people may prefer dark themed websites

A toggle button can be built for the user to select the option of white theme or dark theme 

### Screenshots

![toggle button](https://user-images.githubusercontent.com/97597966/173042640-4019dce1-c1d7-411b-b113-a10f4f41562e.jpeg)

**Comment by emmalearnscode** [comment] 2022-06-10 19:32
Thanks for the suggestion. This is a duplicate of issue #1032 so I'll close this one for now. Feel free to add any additional comments or ideas you have in that thread.

**Closed by emmalearnscode** 2022-06-10 19:32 UTC
Labels: ⭐ goal: addition
