### ISSUE TITLE
Issue with Rendering the Profile Images.

### ISSUE THREAD

**Issue by manavmodi22** [EddieHubCommunity/LinkFree#480] opened 2021-10-08 17:11 UTC
### Description

Apparently, the image loading is quite not normal. Sometimes it gets loaded fully, sometimes it displays the alt text. Normally this should not happen, on a fully functional internet connection. 

### Screenshots

<img width="1364" alt="Screenshot 2021-10-08 at 22 36 01" src="https://user-images.githubusercontent.com/55242552/136596060-0f741e72-fa51-4354-8271-a28d93afb2e5.png">
<img width="1306" alt="Screenshot 2021-10-08 at 22 37 02" src="https://user-images.githubusercontent.com/55242552/136596080-e8fcbd93-4054-4679-8f3c-f475cd52a6c7.png">

### Additional information

N/A

**Comment by GaryNLOL** [comment] 2021-10-08 19:15
I'm not sure, but I don't think this is an error of the website. According to the console, the images don't load because of an error with the status 429 (Too Many Requests), which is probably caused by the limit of requests that GitHub allows.

**Comment by manavmodi22** [comment] 2021-10-08 19:20
@GaryNLOL isn't there any way we can fix it?

**Comment by shashank-indukuri** [comment] 2021-10-08 19:40
Instead of making the fetch for lists.json multiple times, It's ideal to maintain a global state. It may limit the number of requests to the user list.

**Comment by shashank-indukuri** [comment] 2021-10-09 06:41
I have an idea about maintaining the list.json in global state using context hook. But when I tried implementing it, I encountered an another issue while navigating from Profile component to the Home page. The state is resetting during the routing. Any suggestions?

**Comment by shashank-indukuri** [comment] 2021-10-12 03:44
I have a working solution in my local repo to eliminate duplicate network calls for a list and maintaining a global state using Context API. Can I create a PR for this issue?

**Comment by krishguptadev** [comment] 2021-10-12 04:14
> I have a working solution in my local repo to eliminate duplicate network calls for a list and maintaining a global state using Context API. Can I create a PR for this issue? @krishguptadev

Yeah sure!

**Comment by krishguptadev** [comment] 2021-12-09 03:10
Isn't this issue fixed already? 
![image](https://user-images.githubusercontent.com/91655303/145327639-c8d5d449-a8e8-4f1f-80da-438749667095.png)

**Comment by shashank-indukuri** [comment] 2021-12-09 23:39
The pull request is created for it. It has to be reviewed. fix: rendering profile images (#480) #504

**Comment by KendallDoesCoding** [comment] 2022-02-06 14:31
Yes, I tried searching for a profile too and it didnt render and when I reloaded the page it worked.

**Comment by KendallDoesCoding** [comment] 2022-02-07 18:09
I had another kind of issue but simillar to this #1085

**Comment by eddiejaoude** [comment] 2022-05-24 10:02
I think this is due to the rate limit on GitHub's API

We are planning to refactor the home page as the list is so long now

Here is the issue
https://github.com/EddieHubCommunity/LinkFree/issues/1264

**Comment by emmalearnscode** [comment] 2022-05-25 10:23
This should be fixed now with PR #1306

**Closed by emmalearnscode** 2022-05-25 10:23 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix
