### ISSUE TITLE
[BUG] Paid events are not displayed in the "All" event list

### ISSUE THREAD

**Issue by Fly0w** [EddieHubCommunity/LinkFree#7878] opened 2023-06-30 13:37 UTC
### Description

Free events are displayed normally in the "Show All" events, but once you edit an event to make it a paid event, it is not displayed anymore in the list.

However, it remains in your personal events list.

Note that the small icon "paid" or "free" is not displayed either in the Show All list. Cf : #7854 

### Screenshots

![Paid events do not get displayed](https://github.com/EddieHubCommunity/LinkFree/assets/121224710/5810f69d-1c70-4d22-986f-1286ce7da67c)

**Comment by Pradumnasaraf** [comment] 2023-06-30 17:12
It is duplicate of #7854

**Comment by SaraJaoude** [comment] 2023-07-01 02:24
> Hey, the issue is a duplicate of #7854

Thanks @Fly0w for raising and good spot @Pradumnasaraf  - as this is a duplicate I will close.

**Closed by SaraJaoude** 2023-07-01 02:24 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
