### ISSUE TITLE
Name and socials rendering repetitively on navigation

### ISSUE THREAD

**Issue by Ananya2001-an** [EddieHubCommunity/LinkFree#5126] opened 2023-02-27 15:53 UTC
### Description

On switching between the tabs on a user's profile the name and socials get rendered again and again. It's just a little bit distracting.

### Screenshots

![image](https://user-images.githubusercontent.com/55504616/221613149-f051124d-be57-49d4-b36b-560b75660493.png)

https://www.awesomescreenshot.com/video/15158002?key=0dfc8065ede6a2e6c6928ea4396ac472

**Comment by psavan1655** [comment] 2023-02-27 17:52
I would like to contribute to this issue. It would be my first open source contribution. But i have worked with React, Next for over 3 years now. So i am confident that it's a good first issue for me. It would be great if you can assign me this issue. Thanks. Soon  i will also share a video of the solution.

**Comment by psavan1655** [comment] 2023-02-27 18:09
https://www.loom.com/share/c0b4d8c001734d86931668b43d53e51f

I have resolved this issue. It's a performance improvement too. As profile data doesn't get changed too frequently and it is a also a UI heavy component with images, QR Code and stuff. So using a memoized component instead.
Please provide suggestions if any. 

And would be great if you can assign me this issue. If yes i'll create a PR for the same.

**Comment by Ananya2001-an** [comment] 2023-02-27 18:38
> https://www.loom.com/share/c0b4d8c001734d86931668b43d53e51f
> 
> I have resolved this issue. It's a performance improvement too. As profile data doesn't get changed too frequently and it is a also a UI heavy component with images, QR Code and stuff. So using a memoized component instead.
> Please provide suggestions if any. 
> 
> And would be great if you can assign me this issue. If yes i'll create a PR for the same.
> 
> Sorry, i was an enthusiast here, and worked on the issue before resolution of triage, but excited for open-source contributions.

Looks awesome @psavan1655 I am not a maintainer so I can't assign this issue to you but soon someone will look into it and give you the required directions. 😊

**Comment by psavan1655** [comment] 2023-02-27 18:45
> > https://www.loom.com/share/c0b4d8c001734d86931668b43d53e51f
> > I have resolved this issue. It's a performance improvement too. As profile data doesn't get changed too frequently and it is a also a UI heavy component with images, QR Code and stuff. So using a memoized component instead.
> > Please provide suggestions if any.
> > And would be great if you can assign me this issue. If yes i'll create a PR for the same.
> > Sorry, i was an enthusiast here, and worked on the issue before resolution of triage, but excited for open-source contributions.
> 
> Looks awesome @psavan1655 I am not a maintainer so I can't assign this issue to you but soon someone will look into it and give you the required directions. 😊

Thanks man. And thanks for this amazing feeling, i've been working in companies since a long now. but the excitement of working on open-source is something different, and would try doing more and more, Also develop my skills more in the process and help others do the same.

**Comment by Ananya2001-an** [comment] 2023-02-27 18:58
Happy to hear that 🌈

**Comment by SaraJaoude** [comment] 2023-02-28 06:15
@Ananya2001-an Thank you for raising but this is actually a duplicate of an existing Issue: https://github.com/EddieHubCommunity/LinkFree/issues/5003 so I will be closing this. 

@psavan1655 We are pleased that you have chosen EddieHub to make your first open source contribution. In future we would be grateful if you could please follow the procedures we have in place for working on Issues as these have been designed by the maintainers to make sure that the project runs effectively, avoids confusion and also prevents contributors from doing unnecessary or work which will not be used:

1. Wait until an Issue has the label 'status: ready for dev'
2. In the comments to be assigned this Issue. 
3. If the Issue is assigned to you then please make a Pull Request. 

As it appears you have fixed this problem raised in this Issue, please ask for it to be assigned to you here: https://github.com/EddieHubCommunity/LinkFree/issues/5003 and I will assign it to you.

**Comment by SaraJaoude** [comment] 2023-02-28 06:17
> Thanks man. 

@psavan1655 I would suggest you join the EddieHub Discord so that you can learn how we use inclusive language in this community and refrain from calling anyone `man` `guy` `girl` etc. https://discord.com/invite/jZQs6Wu

**Closed by SaraJaoude** 2023-02-28 06:17 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
