### ISSUE TITLE
 [FEATURE] Add Dark Mode

### ISSUE THREAD

**Issue by RaheemAmer** [EddieHubCommunity/LinkFree#1375] opened 2022-06-11 10:07 UTC
### Description

It's a simple one but I think it's gonna make the website looks more awesome

**Comment by emmalearnscode** [comment] 2022-06-11 16:34
Thanks for raising this issue. It's a duplicate of #1032 so feel free to add any further comments there.

**Closed by emmalearnscode** 2022-06-11 16:34 UTC
Labels: ⭐ goal: addition
