### ISSUE TITLE
[BUG] Text not appearing in the dropdown box in profile page  

### ISSUE THREAD

**Issue by coderiksenthil** [EddieHubCommunity/LinkFree#8079] opened 2023-07-09 12:12 UTC
### Description

The website is great but the text in the dropdown isn't visible as you can see in the screenshot. 
Here is the link:- https://linkfree.io/account/manage/profile
and click on layout, you can see the dropdown and this only happens in dark mode, in the light mode, it's not an issue as you can see in the screenshot below

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/66522620/59fc3688-143c-4e18-8c3f-743d84d830b2)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/66522620/a273d4d7-dc55-4c72-941e-d2983ab88469)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/66522620/3681d149-0c37-48b7-bb6a-62b94d7da6ac)

**Comment by amandamartin-dev** [comment] 2023-07-09 18:58
Able to recreate, will open this issue. Appreciate your contribution.

A note for opening issues, please add more details which helps pinpoint and triage the issues.

For example I would have adde a screenshot that showed more context, the link to the page, and that this only happens in dark mode.  Nothing to change! Just some notes for future issues to consider.

**Comment by eddiejaoude** [comment] 2023-07-10 09:44
Thank you for raising, I will close this issue as it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/7939

**Closed by eddiejaoude** 2023-07-10 09:44 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, good first issue
