### ISSUE TITLE
[OTHER] Notify users to update their milestones

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#8155] opened 2023-07-12 07:13 UTC
### What would you like to share?

Milestones inherited from original json data might only be for the year, which means your milestones will now display 1/1/YYYY.

![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/33f5b723-787e-4d90-9acb-42faf3a8def2)

### Additional information

We could put an alert at the top of the page when a user logs in to let them know they should update them.

**Comment by eddiejaoude** [comment] 2023-07-16 19:45
Good idea 👍 

- On the stats page we could check if any of their events have an invalid date then show an alert at the top of the page
- Also on the milestone page, add an error on the item itself

**Comment by anikdhabal** [comment] 2023-07-17 04:23
I want to work on this issue.

**Comment by SaraJaoude** [comment] 2023-07-17 08:04
> I would like to work on this issue

@anikdhabal I have assigned this to you

**Comment by loftwah** [comment] 2023-07-17 12:58
Is this going to be a notification system or a one-off? This could be a functionality that is wanted again in the future.

**Comment by eddiejaoude** [comment] 2023-07-18 08:22
I think we keep this simple just with a visual alert on the page

Later we will have a full on notification system

**Comment by anikdhabal** [comment] 2023-07-21 13:54
> Good idea 👍
> 
> * On the stats page we could check if any of their events have an invalid date then show an alert at the top of the page
> * Also on the milestone page, add an error on the item itself



> Good idea 👍
> 
> * On the stats page we could check if any of their events have an invalid date then show an alert at the top of the page
> * Also on the milestone page, add an error on the item itself

what do you mean by invalid date? Can you elaborate this into more concise?

**Comment by SaraJaoude** [comment] 2023-07-23 10:39
@anikdhabal we encourage asking questions but it seems that you are unclear as to how to proceed, so it is best if this is unassigned from you.  In future please ask questions so that you have a clear understanding as to how to start and progress, before you ask for an issue to be assigned to you.

**Comment by eddiejaoude** [comment] 2023-07-23 10:42
> what do you mean by invalid date? Can you elaborate this into more concise?

The json files allow the use of a string for the date, but we convert this to a date object, however if this fails, we should alert the user to update it to a valid date

**Comment by bikrantjajware** [comment] 2023-07-27 03:48
Do you mean something like this a alert on the top of page
<img width="1330" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/34072248/5f360990-d45d-4d82-b288-b74369348ce3">

**Comment by eddiejaoude** [comment] 2023-07-28 12:36
Yes and also highlight the individual milestone causing the problem

**Comment by bikrantjajware** [comment] 2023-07-28 17:53
okay, how about a squiggly underline. 


> The json files allow the use of a string for the date, but we convert this to a date object, however if this fails, we should alert the user to update it to a valid date

actually the issue mentions milestone.date might only have year (for ex: '2023' ) which is a valid date object (1/1/YYYY).  So i guess what we want is to check if milestone.date is only year. 

what do you think?



please assign me the issue, i would like to work on it

**Comment by eddiejaoude** [comment] 2023-07-28 18:29
> okay, how about a squiggly underline.

it might get missed, let's keep it simple and maybe add a red border around the event item

> actually the issue mentions milestone.date might only have year (for ex: '2023' ) which is a valid date object (1/1/YYYY). So i guess what we want is to check if milestone.date is only year.

@dan-mba what do you think?

**Comment by dan-mba** [comment] 2023-07-28 21:37
> > okay, how about a squiggly underline.
> 
> it might get missed, let's keep it simple and maybe add a red border around the event item
> 
> > actually the issue mentions milestone.date might only have year (for ex: '2023' ) which is a valid date object (1/1/YYYY). So i guess what we want is to check if milestone.date is only year.
> 
> @dan-mba what do you think?

I don't think there is a way to tell if the date is as intended or a converted date.
This would require a significant amount of checking in the `system/reload` API.

Currently the API performs a conversion & if that errors, the date is omitted.
Checking for example that `May 2020 != May 1 2020` is not easily done with the build in Date functions.

Other Date libraries may have functionality for this, but we would need to add a field to the DB to track the errors or modifications.

**Comment by eddiejaoude** [comment] 2023-08-03 15:47
Thanks @dan-mba 👍 

I will close this for now

**Closed by eddiejaoude** 2023-08-03 15:47 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🟧 priority: high, 🔢 points: 3
