### ISSUE TITLE
[BUG] Issue with mobile responsiveness after logging

### ISSUE THREAD

**Issue by aj11anuj** [EddieHubCommunity/LinkFree#8411] opened 2023-07-30 17:42 UTC
### Description

There is an issue, with mobile responsiveness of linkfree profiles.

Before logging to own linkfree profile, when i visit my linkfree profile. It works fine, without any problem.

But after logging to own linkfree profile, there is some extra spacing at right side all over the profile (refer below screenshot)

### Screenshots

**Before logging in**
![Screenshot_2023-07-30-22-29-09-597_com android chrome](https://github.com/EddieHubCommunity/LinkFree/assets/116108975/e2ef6cbb-e8e1-470f-904f-bfb887d57e18)

**After logging in**
![Screenshot_2023-07-30-22-30-01-324_com android chrome](https://github.com/EddieHubCommunity/LinkFree/assets/116108975/a8fbc29f-3572-4d36-b987-66a0313bbbc8)

### Additional information

I have seen this issue on mobile device only, On Desktop it's working fine.

**Comment by SaraJaoude** [comment] 2023-08-01 10:45
Thank you for raising.  This appears to be a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/8393 so I will close this for now.

**Closed by SaraJaoude** 2023-08-01 10:45 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
