### ISSUE TITLE
Two javascript tags in search page

### ISSUE THREAD

**Issue by rohinish404** [EddieHubCommunity/LinkFree#5853] opened 2023-04-05 05:24 UTC
### Description

On the search page, there are two javascript tags with different spellings. When either one is clicked, both gets selected. Are the two tags intentional or is this some bug?
I have attached the screenshot below.

### Screenshots

![Screenshot_20230405_104912](https://user-images.githubusercontent.com/92542124/229988019-99fc822d-ffa5-41b0-acf4-a58872613a6d.jpg)

**Comment by swagataroy30** [comment] 2023-04-05 12:18
This issue seems to be a duplicate of #4676

**Comment by amandamartin-dev** [comment] 2023-04-05 12:24
Closing as a duplicate.  Please remember to search issues before creating a new one.

**Closed by amandamartin-dev** 2023-04-05 12:24 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
