### ISSUE TITLE
feat: Show the name of the person when hovered on the avatar

### ISSUE THREAD

**Issue by Soham041201** [EddieHubCommunity/LinkFree#108] opened 2021-09-13 15:56 UTC

**Comment by Soham041201** [comment] 2021-09-13 15:59
Thinking about adding a feature of showing a name of the person, when the user hovers over the avatar

**Comment by nhcarrigan** [comment] 2021-09-13 16:34
Closing this as duplicate of #96

**Closed by nhcarrigan** 2021-09-13 16:34 UTC
Labels: duplicate
