### ISSUE TITLE
[DOCS] <Improves Events Section>

### ISSUE THREAD

**Issue by kumarankit999** [EddieHubCommunity/LinkFree#6635] opened 2023-05-06 04:45 UTC
### Description

In the Events Section There has been a Single Event ,Which is Written two times like the kubehuddle 2023 (2), We are developer World Congress  (3), Infobit Shift Conference, etc are should be added be only time but it has been Displayed two to three times and it is the Same Event. There should be no Repeat in display of the Events. So that people not be Confused.

![image](https://user-images.githubusercontent.com/111564362/236600339-6df05b5e-ddf3-40d9-9242-621bca5da3fa.png)

### Screenshots

![image](https://user-images.githubusercontent.com/111564362/236600051-8c20ba0e-1c97-4d9e-b6de-5677f1cdbb15.png)

![image](https://user-images.githubusercontent.com/111564362/236600059-720c9a18-8ce9-4a32-bb45-6a96593228e7.png)

**Comment by eddiejaoude** [comment] 2023-05-06 07:16
Thank you for raising 👍 but I will close this issue as it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2600

Please have a read of our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Closed by eddiejaoude** 2023-05-06 07:16 UTC
Labels: 🚦 status: awaiting triage, 📄 aspect: text
