### ISSUE TITLE
[BUG] Preventing keydown event capture when input is focused

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/LinkFree#8661] opened 2023-08-15 19:24 UTC
## Expected Behavior:
When `search` input element is focused on the search page, keydown events should not be captured, allowing users to interact with the input without unintended side effects.

## Actual Behavior:
Currently, when the `search` input is focused on the search page, keydown events are still being captured, which can lead to unexpected behavior and conflicts with user input.

## Steps to Reproduce:

* Open the [linkfree.io](linkfree.io)
* Navigate to the search page
* Select any tags. (f.e. - `javascript`)
* Focus on `search` input element.
* Attempt to type right arrow(&rarr;) into the input and pagination will go next page

### Additional information

Would love to fix this

**Comment by SaraJaoude** [comment] 2023-08-16 17:16
Could you please provide a video or screenshots as we are having trouble understanding what the problem is.

**Comment by badrivlog** [comment] 2023-08-16 17:54
> Could you please provide a video or screenshots as we are having trouble understanding what the problem is.

Yes, in the search page when search input is focused,  press `right` or `left` arrow key notice the pagination goes to different pages 


https://github.com/EddieHubCommunity/LinkFree/assets/73095526/6f120617-d2e7-4f06-8f1a-70b4b604f2f3

**Comment by eddiejaoude** [comment] 2023-08-17 07:57
> on the search page when search input is focused, press right or left arrow key notice the pagination goes to different pages. I think this is the unexpected behaviour

Thank you for this clarification 👍 yes this is a bug, I will assign to you

**Comment by KSSaiTeja** [comment] 2023-08-18 07:52
@badrivlog you've a great work, but i didin't notice what you've done. so i also fixed same issue with my approach. so as i am  a beginner could you please cooperate with my PR. because it would be more motivatinal for contributing the upcoming issues

**Comment by KSSaiTeja** [comment] 2023-08-18 07:53
> @badrivlog you've a great work, but i didin't notice what you've done. so i also fixed same issue with my approach. so as i am a beginner could you please cooperate with my PR. because it would be more motivatinal for contributing the upcoming issues

Hope you reply back with positive opinion

**Comment by SaraJaoude** [comment] 2023-08-18 09:59
@KSSaiTeja I sent to you the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) a few days ago and explained to you that this is not how collaboration is done on this project. You mentioned that you would read the Guide and follow our rules but you have not.  You mention that as a first time contributor you are finding this confusing - please let maintainers know what part of the Contributing Guide is not clear and we will be very pleased to explain this further.

I will be closing your PR https://github.com/EddieHubCommunity/LinkFree/pull/8691

**Comment by SaraJaoude** [comment] 2023-08-18 09:59
@badrivlog please disregard the above messages and references to PR https://github.com/EddieHubCommunity/LinkFree/pull/8691

**Comment by SaraJaoude** [comment] 2023-08-18 09:59
@badrivlog please disregard the above messages and references to PR https://github.com/EddieHubCommunity/LinkFree/pull/8691

**Comment by KSSaiTeja** [comment] 2023-08-18 10:03
please assign me this issue... i will work upon it. this is the last time please excuse me and give one oppurtunity to work on this.

As i have already worked on this, please consider that and i promise you i won't repeat this again..

due to this mistake another PR is also closed please dont do this..

Excuse me for this. I won't repeat again..

please assign me this

**Comment by eddiejaoude** [comment] 2023-08-18 10:10
> please assign me this issue... i will work upon it. this is the last time please excuse me and give one oppurtunity to work on this.
> 
> As i have already worked on this, please consider that and i promise you i won't repeat this again..
> 
> due to this mistake another PR is also closed please dont do this..
> 
> Excuse me for this. I won't repeat again..
> 
> please assign me this

@KSSaiTeja As explained to you before, the assignee of this issue has also already raised a pull request before yours. Please stop creating confusion, noise and extra work for everyone within the project

**Closed** 2023-08-21 08:13 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, 🟧 priority: high, 🔢 points: 2
