### ISSUE TITLE
[FEATURE] Filter by coding language

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1070] opened 2022-02-06 14:47 UTC
### Description

In the file where users need to make their profile, they can put the languages they code in, for eg, this is what I will put in:

```"languages": "HTML", "CSS", "JAVASCRIPT", "PYTHON"```

Then, a button like the "Profile Type" button on the main page of Linkfree to filter out the languages and show the people that put those languages in their profile.

Idk, what the purpose of Linkfree is, if its a database or coders, contributors to EddieHubCommunity, etc. But, I'm assuming its also to get contributors to your project? If it is, then this will really be good because you can filter out the language you want help with, and contact the required people who know the coding language.

**Comment by emmalearnscode** [comment] 2022-02-06 19:08
Thanks for raising the issue, it seems to be a duplicate of #802 so I’ll close this one for now. Feel free to add your comments there instead

**Closed by emmalearnscode** 2022-02-06 19:08 UTC
Labels: ⭐ goal: addition

**Comment by KendallDoesCoding** [comment] 2022-02-06 19:11
> In the file where users need to make their profile, they can put the languages they code in, for eg, this is what I will put in:
> 
> `"languages": "HTML", "CSS", "JAVASCRIPT", "PYTHON"`
> 
> Then, a button like the "Profile Type" button on the main page of Linkfree to filter out the languages and show the people that put those languages in their profile.
> 
> Idk, what the purpose of Linkfree is, if its a database or coders, contributors to EddieHubCommunity, etc. But, I'm assuming its also to get contributors to your project? If it is, then this will really be good because you can filter out the language you want help with, and contact the required people who know the coding language.

Ok, thanks a lot.
