### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by whoiskekeanyway** [EddieHubCommunity/LinkFree#978] opened 2022-01-12 14:39 UTC
### What would you like to share?

The SSL Certificate at http://linkfree.eddiehub.org/ has expired. Please look into it.
@eddiejaoude 
Thanks

<img width="318" alt="Screenshot 2022-01-12 at 15 51 51" src="https://user-images.githubusercontent.com/71834585/149160946-8b083d0b-7c34-4acb-b11e-6dac0b7baec1.png">

**Comment by krishguptadev** [comment] 2022-01-12 15:19
Duplicate of #197

**Comment by emmalearnscode** [comment] 2022-01-13 08:53
I'll close this as it's a duplicate but thanks for flagging the issue!

**Closed by emmalearnscode** 2022-01-13 08:53 UTC
Labels: 🚦 status: awaiting triage

**Comment by eddiejaoude** [comment] 2022-01-14 01:38
Thanks all for collaborating 👍 we will fix soon
