### ISSUE TITLE
[FEATURE] Change cursor to pointer for QR code

### ISSUE THREAD

**Issue by Njong392** [EddieHubCommunity/LinkFree#2267] opened 2022-11-23 20:34 UTC
### Description

I noticed the recent addition of a QR code to all user profiles. The hopping animation is cool, but what if on hover, we changed the cursor to a pointer to further show users that it's clickable? Not sure how this would be accessibility-wise, but 

### Screenshots

![QR cod around my name with pointer over it on hover](https://user-images.githubusercontent.com/81039882/203641144-0761b5b6-870b-4c20-b8fe-bb7198f50fad.png)

**Comment by ThorOnTheRocks** [comment] 2022-11-24 08:36
Great idea! I think as long as it's keyboard-focusable it should be fine regarding accessibility...but not 100% sure. 
Let me know if nobody works on that I would love to do it

**Comment by Njong392** [comment] 2022-11-24 10:56
I'm just now waiting to hear from the maintainers. But sure. You can take the issue if they approve it 😇

**Comment by rwiteshbera** [comment] 2022-11-26 18:59
I love to work on it. hi, @Njong392 , Will you please assign me this issue?

**Comment by amandamartin-dev** [comment] 2022-11-28 22:21
I opened an issue for this a few days ago..  is there a way to combine into one so we don't have duplicate work? 

Issue #2250

**Comment by eddiejaoude** [comment] 2022-11-28 22:36
Thanks all for the great idea and discussions. I will close this as it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2250

**Closed by eddiejaoude** 2022-11-28 22:36 UTC
Labels: ⭐ goal: addition
