### ISSUE TITLE
Getting Username on Hover over Avatar

### ISSUE THREAD

**Issue by aayush89890** [EddieHubCommunity/LinkFree#222] opened 2021-09-17 04:15 UTC
We can show the username once a person hover over an Avatar.

## Expected Behaviour
![Screenshot (59)](https://user-images.githubusercontent.com/37421316/133723100-809ef0af-d92e-4279-bf1e-837e21e8f20c.png)

**Comment by ShlokMohanty** [comment] 2021-09-17 05:46
@aayush89890 , @eddiejaoude is this showing name when hovered over done or still needs to be done ?

**Comment by aayush89890** [comment] 2021-09-17 06:17
> @aayush89890 , @eddiejaoude is this showing name when hovered over done or still needs to be done ?

Hi @ShlokMohanty this issue needs to be fixed.
If you want to give it a try go ahead.

**Comment by Cahllagerfeld** [comment] 2021-09-17 06:53
its a duplicate of #96

**Comment by Cahllagerfeld** [comment] 2021-09-17 06:57
closed, reason see above (:

**Closed by Cahllagerfeld** 2021-09-17 06:57 UTC
