### ISSUE TITLE
[ DOCS ] Readme Restructure 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [EddieHubCommunity/LinkFree#111] opened 2021-09-13 16:13 UTC
We can add the fork or clone guidelines like setup details in `contribution.md` so we can get more space to express our idea and our purpose of this project.

**Comment by nhcarrigan** [comment] 2021-09-13 16:36
Closing as duplicate of #24

**Closed by nhcarrigan** 2021-09-13 16:36 UTC
