### ISSUE TITLE
[UI/UX]  Proposal for UX/UI Changes

### ISSUE THREAD

**Issue by moonLight-7k** [EddieHubCommunity/LinkFree#6228] opened 2023-04-20 10:40 UTC
#### The filter buttons [here](https://linkfree.io/map) are not of same height and clear filter btn is too large
![Screenshot (28)](https://user-images.githubusercontent.com/90507998/233342144-5c3437d9-e8db-45c2-9271-81527c775654.png)

#### It could be better like this 
![Frame 1](https://user-images.githubusercontent.com/90507998/233342346-ee82bcfb-1ce4-4ef2-8caf-27170b44cc3b.png)

**Comment by eddiejaoude** [comment] 2023-04-21 05:54
Thank you for raising the issue, but the title of the issue is not clear?

The screenshots help understand the idea of the issue. However I am not sure if change the button to look like a tag makes sense, as it is confusing, plus the button would then change everywhere else on the app to look like a tag

I think there might be other options to consider here, maybe moving the button? I will unlock this issue and leave it open with the label for `discussion`

**Comment by at-the-vr** [comment] 2023-04-22 09:56
The filter buttons(divs actually) have same height of 36px (the container div itself goes to 52px) (got it from Inspect Element).
As far as the Clear Filters Button goes, the large size indicates it has more importance (essentially its operations are one level up than the rest of the following buttons in that line) and is completely valid

**Comment by moonLight-7k** [comment] 2023-04-22 17:42
Yes, you are right @at-the-vr  the height of the btn's are same. But some how while looking at the btn's it dosen't give the best experience ( maybe bcoz they are little small). I think  that the 'line-height' in '.text-sm' should ~1.9rem, it makes the btn look better and easy for user.

**Comment by amandamartin-dev** [comment] 2023-04-26 20:51
+1 to @eddiejaoude suggestion that the tags should be left alone as they are used multiple places throughout the application (and are indeed all the same height) but we could propose a different style and location for the clear button.  

I do also agree with @at-the-vr that we would want the clear to be prominent so it is easily discoverable but no, it is not the prettiest button currently.

**Comment by SaraJaoude** [comment] 2023-08-01 10:05
Rebranding has started with a design company, so this will improved soon.  I will therefore close this Issue for now.

**Closed by SaraJaoude** 2023-08-01 10:05 UTC
Labels: 🚦 status: awaiting triage, 💬 talk: discussion
