### ISSUE TITLE
[BUG] <Repo dates are not visible until hover>

### ISSUE THREAD

**Issue by rizahmeds** [EddieHubCommunity/LinkFree#8481] opened 2023-08-03 12:52 UTC
### On Community Repos Page:
Dates alongside of repo url is not visible in dark mode until hover done on list item.

### Screenshots

Before hover to repo list.
<img width="1270" alt="Screenshot 2023-08-03 at 17 58 48" src="https://github.com/EddieHubCommunity/LinkFree/assets/24509202/a89d0ffb-0f50-4acc-896a-b589be2fb657">

After hover to repo list.
<img width="1278" alt="Screenshot 2023-08-03 at 17 58 52" src="https://github.com/EddieHubCommunity/LinkFree/assets/24509202/28faf7ea-026d-4425-9432-c9b9c05ffd2a">

**Comment by ChinmayMhatre** [comment] 2023-08-03 14:50
Duplicate of #8441

**Closed** 2023-08-03 14:50 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
