### ISSUE TITLE
Camouflaged close btn of 'Link Copied' dialog box.

### ISSUE THREAD

**Issue by digambar-t7** [EddieHubCommunity/LinkFree#950] opened 2022-01-09 18:36 UTC
### Description

When we are trying to copy link of any profile to the clipboard, a dialog box pops up. The close btn of this dialog box(green box in the ss) is not visible enough. It has been camouflaged with the background. 

### Screenshots

![Screenshot from 2022-01-10 00-04-15](https://user-images.githubusercontent.com/92970968/148695721-dd36b635-7e69-4241-a1fd-3542883b9e11.png)

**Comment by emmalearnscode** [comment] 2022-01-09 18:43
I don't think the dialog (toast) has a close button, it's programmed to automatically disappear after a few seconds.

**Comment by digambar-t7** [comment] 2022-01-09 18:49
Yeah it does closes after few seconds but there's still a close-button. Either we must completely  remove it and let the dialog-box close automatically or must improve the button. Because it points out the incompleteness of the design.

**Comment by emmalearnscode** [comment] 2022-01-09 18:53
I think I just realised what the problem is and it's hopefully being solved in another pull request. When we updated the icons package to react icons the prime icons got removed. However some of the prime components use prime icons as part of their design and are now not showing correctly. The person working on the profile filter noticed this earlier and has added it back in so hopefully when that pull request gets merged then this problem will be solved too.

**Comment by digambar-t7** [comment] 2022-01-09 18:56
Okay that will be better

**Comment by emmalearnscode** [comment] 2022-01-12 11:05
This got fixed in another pull request so I'll close this one. Thanks for raising the issue!

**Closed by emmalearnscode** 2022-01-12 11:05 UTC
Labels: 🚧 status: blocked, 🛠 goal: fix
