### ISSUE TITLE
[FEATURE] Hover effects in 3 divs ,

### ISSUE THREAD

**Issue by IPratikMali** [EddieHubCommunity/LinkFree#4863] opened 2023-02-16 06:34 UTC
### Description

Add Box-shadow on Hover effect for following div
1) Active Users
2) Profile Views
3) Links Clicked

### Screenshots

![hoverboxshadow](https://user-images.githubusercontent.com/100037271/219286596-2dca53f9-eafd-4b5a-856d-ac674e259e88.png)

 
https://user-images.githubusercontent.com/100037271/219933276-e85cce5e-70a6-4950-81eb-49413b7a9787.mp4

**Comment by Aadarsh805** [comment] 2023-02-16 13:19
But those are not clickable, adding hover on those might cause confusion for users

**Comment by Jayakrishna2b** [comment] 2023-02-16 16:56
but making clickable makes user experince better(as well as adding hover also)

**Comment by ManishBisht777** [comment] 2023-02-17 03:50
agree with @Aadarsh805 as the elements have no interaction I don't think there is a need to add a hover or cursor pointer

**Comment by HarshDeep61034** [comment] 2023-02-17 06:39
I don't think so It's a good idea to add box shadow on non-clickable divs.

**Comment by Faizan711** [comment] 2023-02-17 06:42
@IPratikMali should i work on this issue, please clarify

**Comment by Aadarsh805** [comment] 2023-02-17 08:26
> @IPratikMali should i work on this issue, please clarify

no no, as you can see the issue is labeled `status: awaiting triage`
if approved, it'll have the label `status: ready for dev`, only then you should make a pr

**Comment by Faizan711** [comment] 2023-02-17 08:29
Ok no problem

**Comment by shubhsharma19** [comment] 2023-02-18 13:00
> But those are not clickable, adding hover on those might cause confusion for users

Agreed, There is no need to make it hover, however a color change or some microinteractions can make it more interactive and more attractive. There are many options like color change, animation, etc. :D

**Comment by ManishBisht777** [comment] 2023-02-18 13:10
> > But those are not clickable, adding hover on those might cause confusion for users
> 
> Agreed, There is no need to make it hover, however a color change or some microinteractions can make it more interactive and more attractive to users. There are many options like color change, animation, etc. :D

Interaction to plane text even though they are very less. this can create a poor user experience as users may try to interact with something that is not meant to be interacted with.

if we want to make them attractive 
we can add a counter to them
ex- instead of showing 3.5K it can start from 0 to 3.5k

but still it does seems to me a bad user experience as it gives a sense that views/users are increasing in real-time

**Comment by shubhsharma19** [comment] 2023-02-18 13:23
> > > But those are not clickable, adding hover on those might cause confusion for users
> > 
> > 
> > Agreed, There is no need to make it hover, however a color change or some microinteractions can make it more interactive and more attractive to users. There are many options like color change, animation, etc. :D
> 
> Interaction to plane text even though they are very less. this can create a poor user experience as users may try to interact with something that is not meant to be interacted with.
> 
> if we want to make them attractive we can add a counter to them ex- instead of showing 3.5K it can start from 0 to 3.5k
> 
> but still it does seems to me a bad user experience as it gives a sense that views/users are increasing in real-time

Any thing that moves attract user's attention so I do agree with your statement however simple microinteractions does not always mean it's meant to be clicked. For example you can checkout this: https://linktr.ee/ 

You can see how much interactive LinkTree website is. Its just my opinion :)

**Comment by IPratikMali** [comment] 2023-02-19 06:56
> But those are not clickable, adding hover on those might cause confusion for users

Hover is not limited to clickable items only, we can use it to enhance user experience. please see the video that i have added in issue and give a feedback

**Comment by IPratikMali** [comment] 2023-02-19 06:57
> > > > But those are not clickable, adding hover on those might cause confusion for users
> > > 
> > > 
> > > Agreed, There is no need to make it hover, however a color change or some microinteractions can make it more interactive and more attractive to users. There are many options like color change, animation, etc. :D
> > 
> > 
> > Interaction to plane text even though they are very less. this can create a poor user experience as users may try to interact with something that is not meant to be interacted with.
> > if we want to make them attractive we can add a counter to them ex- instead of showing 3.5K it can start from 0 to 3.5k
> > but still it does seems to me a bad user experience as it gives a sense that views/users are increasing in real-time
> 
> Any thing that moves attract user's attention so I do agree with your statement however simple microinteractions does not always mean it's meant to be clicked. For example you can checkout this: https://linktr.ee/
> 
> You can see how much interactive LinkTree website is. Its just my opinion :)

Linktree is full of animation and hover effects

**Comment by IPratikMali** [comment] 2023-02-19 07:00
> agree with @Aadarsh805 as the elements have no interaction I don't think there is a need to add a hover or cursor pointer

i agree , but we can add stats/graphs after clicking on those divs.
like how many users joined on what day ,  how many active users on what day at what time like that

**Comment by eddiejaoude** [comment] 2023-02-19 21:25
We might have more graphs for these stats in the future, which would these clickable. But for now I agree, these cards don't need an effect and could cause some confusion.

Thank you for the suggestion and great collaboration, but I will close this for now.

**Closed by eddiejaoude** 2023-02-19 21:25 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
