### ISSUE TITLE
Link is not being copied to the clipboard

### ISSUE THREAD

**Issue by Mohith234** [EddieHubCommunity/LinkFree#1037] opened 2022-01-26 18:09 UTC
### Description

While looking into the website of **LinkFree**, I figured out that when we click on the share button on anyone's profile ,
A popup appears showing 4 options , and upon clicking
- Facebook : Opens their Facebook profile to share the **Linkfree profile**.
- Twitter : Opens their Twitter profile to share the **Linkfree profile**.
- Linkedin : Opens their Linkedin profile to share the **Linkfree profile**.
- Link Button : clicking on this, the **Linkfree profile** link must be copied to clipboard. 

### [BUG]
Using the **Link button** - It's not copying the link to my clipboard.

**Comment by emmalearnscode** [comment] 2022-01-26 20:10
Thanks for raising this issue, we are aware of it and the fix requires an upgrade to https so it’s currently blocked until Eddie gets some help to upgrade it. I’ll close this as it’s a duplicate of #946

**Closed by emmalearnscode** 2022-01-26 20:10 UTC
Labels: duplicate, 🛠 goal: fix
