### ISSUE TITLE
[Bug] GitHub social icon not visible

### ISSUE THREAD

**Issue by Anmol-Baranwal** [EddieHubCommunity/LinkFree#7411] opened 2023-06-06 07:30 UTC
### Description

Recently, I noticed that when visiting https://linkfree.io/Anmol-Baranwal, the GitHub icon at the top is not visible, while other icons such as Dribbble and Dev are clearly visible. Please refer to the following image for a visual representation: 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/74038190/8fadb472-3087-4617-a4bb-429831becbfa)

### Additional information

You can access my profile data at https://github.com/EddieHubCommunity/LinkFree/blob/main/data/Anmol-Baranwal.json.

Regarding the issue you mentioned, it appears that the GitHub icon is not visible on the LinkFree profile page. For a visual representation of the problem, please refer to the following image:

**Comment by eddiejaoude** [comment] 2023-06-06 10:16
Thank you for creating a well-written issue with links to your profile and json file etc 💯 

This is not a bug, you have your GitHub url multiple times and we de-duplicate links - by unique url. So I will unlock and close this issue, but any questions please let us know

**Closed by eddiejaoude** 2023-06-06 10:16 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
