### ISSUE TITLE
Align Home Page Avatars To Center

### ISSUE THREAD

**Issue by aayush89890** [EddieHubCommunity/LinkFree#214] opened 2021-09-16 15:09 UTC
### **Home Page Avatars are not alligned to Center.**

![image](https://user-images.githubusercontent.com/37421316/133636916-7bedef77-7ed9-47fb-a87a-7a111d0d60c2.png)

### **Expected:**

![image](https://user-images.githubusercontent.com/37421316/133637107-3062010e-dde1-4928-9cfe-944a58f6df55.png)

**Comment by FayasNoushad** [comment] 2021-09-16 15:14
Duplicate of #107

**Comment by ShlokMohanty** [comment] 2021-09-17 05:52
@aayush89890 i guess the extra white space should also be reduced it looks like only the upper half is filled and there's a lot of space below the icons ? whats your thought on this @FayasNoushad ?

**Closed** 2021-09-17 06:24 UTC

**Comment by aayush89890** [comment] 2021-09-17 06:32
> @aayush89890 i guess the extra white space should also be reduced it looks like only the upper half is filled and there's a lot of space below the icons ? whats your thought on this @FayasNoushad ?

I agree with you point @ShlokMohanty . We can increase the margin from 10px to 1em It will be dynamic and It will look good.
Attaching Screenshot for reference.
We can open a new issue, Let me know I will open the issue.

![image](https://user-images.githubusercontent.com/37421316/133735374-03f03105-ce3e-48dd-b5a3-a28db024fe5a.png)

**Comment by ShlokMohanty** [comment] 2021-09-17 07:06
@aayush89890 i guess we should open this issue of removing white space so you can go ahead

**Comment by aayush89890** [comment] 2021-09-17 08:17
> @aayush89890 i guess we should open this issue of removing white space so you can go ahead

Done #225
