### ISSUE TITLE
GitHub links - Redirect to a new tab

### ISSUE THREAD

**Issue by YOKESHCR** [EddieHubCommunity/LinkFree#6763] opened 2023-05-11 18:51 UTC
### Description

The Github links which are present in the footer when clicked can be made to be opened in a new tab , instead of redirecting. The only Giithub link which opens in a new tab are the one which is present in the nav-bar icon and the user's Github profile.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/27686539/c72304a2-e0b2-4dd3-8355-dd7e135bc651)

**Comment by eddiejaoude** [comment] 2023-05-11 20:45
Thanks for raising, yes external links should open in a new tab 👍

**Comment by HassanTanveer** [comment] 2023-05-11 23:05
Hey, can you assign this issue to me?

**Comment by eddiejaoude** [comment] 2023-05-12 02:09
Sure, assigned @HassanTanveer - please note my comment above, it should only open in new tab for external links

**Comment by HassanTanveer** [comment] 2023-05-12 08:51
Thanks, I understand

**Comment by kaafivikrant** [comment] 2023-05-12 11:16
Hey, @eddiejaoude  you assign this issue to me?

I have tested the code with the changes.

**Comment by eddiejaoude** [comment] 2023-05-12 15:09
> Hey, @eddiejaoude you assign this issue to me?
> 
> I have tested the code with the changes.

@kaafivikrant the issue is already assigned, please read the replies just above yours

**Comment by kaafivikrant** [comment] 2023-05-12 16:03
Sure

**Closed** 2023-05-13 13:35 UTC
Labels: ⭐ goal: addition, 🏁 status: ready for dev, good first issue, 🔢 points: 1
