### ISSUE TITLE
[DOCS] fixing documentation

### ISSUE THREAD

**Issue by iamvbenz49** [EddieHubCommunity/LinkFree#6124] opened 2023-04-16 08:46 UTC
### Description

![CYCLE](https://user-images.githubusercontent.com/93785572/232287336-08ffb804-1071-4c38-ae1a-286ec413ac6e.png)

https://linkfree.eddiehub.io/docs/contributing/maintainers

I think we should change it to  `package-lock.json`

**Comment by jainamthakkar** [comment] 2023-04-16 10:06
i am new to opensource and i want to contribute can you please assign me this issue

**Comment by pratham-yuxo** [comment] 2023-04-16 10:09
> i am new to opensource and i want to contribute can you please assign me this issue

First read the contribution guidelines, don't ask for assigning if the issue is not `ready to dev`.

**Comment by iamvbenz49** [comment] 2023-04-16 10:10
> i am new to opensource and i want to contribute can you please assign me this issue

Hey we shouldn't ask the maintainers to assign the issues if it's status don't have ready to dev tag

Refer this https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by pratham-yuxo** [comment] 2023-04-16 10:39
Can I work on this issue?

**Comment by eddiejaoude** [comment] 2023-04-16 10:39
Good spot @iamvbenz49 👍  (and thank you for mentioning the contributing guideline link)

@pratham-yuxo thank you for sharing information on our contributing guidelines, please include the link next time

**Comment by iamvbenz49** [comment] 2023-04-16 10:40
Can I work on this issue?

**Comment by eddiejaoude** [comment] 2023-04-16 10:41
> Can I work on this issue?

@pratham-yuxo you have had a good first issue already recently, it is better to let other new people to the project a chance with a `good first issue`

**Comment by eddiejaoude** [comment] 2023-04-16 10:43
Same response to you @iamvbenz49 , let's give other people new to the project to work on a good first issue

**Comment by pratham-yuxo** [comment] 2023-04-16 10:43
> > Can I work on this issue?
> 
> @pratham-yuxo you have had a good first issue already recently, it is better to let other new people to the project a chance with a `good first issue`

Okay, I will work on some other issue.

**Comment by iamvbenz49** [comment] 2023-04-16 10:43
> Same response to you @iamvbenz49 , let's give other people new to the project to work on a good first issue

Sure !!

**Comment by jainamthakkar** [comment] 2023-04-16 10:46
> > i am new to opensource and i want to contribute can you please assign me this issue
> 
> Hey we shouldn't ask the maintainers to assign the issues if its status don't have ready to dev tag
> 
> Refer this https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

okay i will keep this in mind. thanks @iamvbenz49

**Comment by ZEUS-03** [comment] 2023-04-16 10:46
hey! I wanna contribute. Will be a good place to start.

**Comment by eddiejaoude** [comment] 2023-04-16 10:49
Thank you for understanding @pratham-yuxo and @iamvbenz49 👍 

@jainamthakkar you haven't contributed to LinkFree yet, would you still like this issue? Otherwise I can assign it to someone else

**Comment by jainamthakkar** [comment] 2023-04-16 10:51
yes i want to contribute

**Comment by eddiejaoude** [comment] 2023-04-16 10:53
ok I have assigned it to you @jainamthakkar 

@ZEUS-03 have a look at out for other open issues that are not assigned with the label `status: ready for dev`

**Comment by jainamthakkar** [comment] 2023-04-16 10:56
thanks @eddiejaoude

**Comment by ZEUS-03** [comment] 2023-04-16 10:59
@eddiejaoude Yeah sure!

**Closed** 2023-04-16 12:30 UTC
Labels: 🏁 status: ready for dev, 🤖 aspect: dx, good first issue, 🔢 points: 1, 📄 aspect: text
