### ISSUE TITLE
Audio pronunciation feature 

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#8617] opened 2023-08-12 15:54 UTC
### Description

I think it would be helpful to have a feature where users who use their real name add a recording of them saying their last name. That way people who meet them in real life can pronounce it correctly.

**Comment by SaraJaoude** [comment] 2023-08-13 10:23
I will close this as this is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/935

**Closed by SaraJaoude** 2023-08-13 10:23 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
