### ISSUE TITLE
[FEATURE] Add Showwcase Icon

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/LinkFree#1043] opened 2022-01-28 14:22 UTC
### Description

We can add the [Showwcase](https://showwcase.com/) in the social icons. Showwcase is a professional network built for developers to connect, build community, and find new opportunities.

### Screenshots

It's a showwcase profile page of [Tapas Adhikary](https://www.showwcase.com/atapas398)

![showwcase profile page](https://user-images.githubusercontent.com/74750414/151562682-d5baf9ff-c205-43ca-8ebf-b552e0a091a8.gif)

### Additional information

I found this logo from [Showwcase About Page](https://www.about.showwcase.com/) format (webp)
![Showwcase Logo](https://static.wixstatic.com/media/553d6a_3aaca7b417254e7796629310652ed784~mv2.png/v1/fill/w_100,h_100,al_c,q_85,usm_4.00_1.00_0.00/ShowwcasLogo100x100.webp)

**Comment by vasantisuthar** [comment] 2022-01-28 15:26
I want to work on this issue can you assign me @emmalearnscode

**Comment by emmalearnscode** [comment] 2022-01-28 16:27
Sure. When adding an icon it needs adding in 3 places. 
1. It needs importing from react icons and adding to the switch in GetIcons.js, 
2. it needs a color code adding in config/links.json 
3. and it needs adding to the readme. 

The first 2 files are in alphabetical order, readme is not yet ordered so it can be placed anywhere.

**Comment by vikasganiga05** [comment] 2022-01-31 14:52
Hey, @vasantisuthar Do you need any help with this? Let me know.

**Comment by krshdev** [comment] 2022-01-31 14:55
Hey @vikasganiga05, Looks like their PR has been merged already, this issue hasn't been closed yet, so could you or one of the maintainers, do the neatful?

**Comment by vikasganiga05** [comment] 2022-01-31 15:23
> Hey @vikasganiga05, Looks like their PR has been merged already, this issue hasn't been closed yet, so could you or one of the maintainers, do the neatful?

No, The showwcase icon is not added to `README.md`, `src/config/links.json` and `src/Components/Icons/GetIcons.js`.

**Comment by krshdev** [comment] 2022-01-31 15:40
I got confused because of the merged PR mentioned 😅 Sorry about that.

**Comment by vasantisuthar** [comment] 2022-01-31 17:24
hey @vikasganiga05, I am working on it, if I ran into any issue, I'll ask. Thanks

**Comment by vikasganiga05** [comment] 2022-01-31 18:59
> I got confused because of the merged PR mentioned sweat_smile Sorry about that.

It's okay. :smile:

**Comment by vikasganiga05** [comment] 2022-01-31 19:00
> hey @vikasganiga05, I am working on it, if I ran into any issue, I'll ask. Thanks

That sounds great :+1:

**Comment by schmelto** [comment] 2022-02-28 13:49
@vasantisuthar are you still working on this?

**Comment by vasantisuthar** [comment] 2022-02-28 14:57
The showwcase icon is not on any font illustration platform so I have created an issue in font-awesome for the icon to be added. Here is the link to the issue https://github.com/FortAwesome/Font-Awesome/issues/18631, and we can vote it so the icon can be added shortly.

**Comment by ayushhagarwal** [comment] 2022-11-01 08:59
Hello @vikasganiga05 , I see the issue is not closed. Is any work still pending here, if Yes I would like to work on it. 

Thanks!

**Comment by eddiejaoude** [comment] 2022-11-05 23:01
2 PRs have been merged, so I think this issue is now complete.

**Closed by eddiejaoude** 2022-11-05 23:01 UTC
Labels: ⭐ goal: addition, 💻 aspect: code, 🏁 status: ready for dev, 🟩 priority: low, 🔢 points: 1
