### ISSUE TITLE
[FEATURE] PWA version of Linkfree

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/LinkFree#2277] opened 2022-11-25 22:47 UTC
### Description

Hi there. I think it would be great for there to be a mobile version of Linkfree, just in case if users need to make changes to their profile but via their smartphone or tablet.

**Comment by mohit1607** [comment] 2022-12-29 07:06
I would like to work on this issue adding pwa for mobile -view.

**Comment by CBID2** [comment] 2022-12-29 08:19
> I would like to work on this issue adding pwa for mobile -view.

Great @mohit1607. I’ll create a file on Replit we can do to a rough draft.

**Comment by eddiejaoude** [comment] 2023-01-15 21:15
Closing this as a duplicate of this issue https://github.com/EddieHubCommunity/LinkFree/issues/2278

**Closed by eddiejaoude** 2023-01-15 21:15 UTC
Labels: ⭐ goal: addition, 💬 talk: discussion
