### ISSUE TITLE
[FEATURE] To have a dark theme in LinkFree

### ISSUE THREAD

**Issue by everydaycodings** [EddieHubCommunity/LinkFree#2957] opened 2023-01-09 16:37 UTC

**Comment by immortalAbdul01** [comment] 2023-01-09 17:05
literally I was thinking the same thing

**Comment by HarshDeep61034** [comment] 2023-01-09 17:45
i was also thinking the same

**Comment by thevinitgupta** [comment] 2023-01-10 04:56
This will be a great addition.
Using Global variables this can be achieved.
Another way would be to use local storage on the user's browser and check the theme before the app is mounted.

**Comment by shubhsharma19** [comment] 2023-01-10 06:44
Same here haha!

**Comment by s4shantanu** [comment] 2023-01-11 03:44
I was thinking the same thing Actually

**Comment by eddiejaoude** [comment] 2023-01-12 00:52
Themes would be good 👍

**Comment by shubhsharma19** [comment] 2023-01-12 06:12
I think there could be an option of like changing themes based on your browser settings maybe, or 2 light themes and 2 dark themes. That would be awesome!! 🎉

**Comment by ManishBisht777** [comment] 2023-01-13 09:25
1) Background customize ( #3317 ) 
       maybe we can provide some given sets of background images to use instead of the user uploading them.

2) Dark theme ( #2957 )

3) Different ways to show links/cards/milestones etc ( #2214 ) 
 
These are 3 Customization ideas for the profiles.

 @eddiejaoude Any Suggesstions?

**Comment by Aadarsh805** [comment] 2023-01-13 14:16
> 

Yes the user providing the background image can cause some displaying issues like the text will not be visible if the user uses a dark background

**Comment by Aadarsh805** [comment] 2023-01-13 14:16
> 1. Background customize ( [[FEATURE]  Background image/ Wallpaper with theme toggle #3317](https://github.com/EddieHubCommunity/LinkFree/issues/3317) )
>    maybe we can provide some given sets of background images to use instead of the user uploading them.
> 2. Dark theme ( [[FEATURE] To have a dark theme in LinkFree #2957](https://github.com/EddieHubCommunity/LinkFree/issues/2957) )
> 3. Different ways to show links/cards/milestones etc ( [Feature: Socials section design #2214](https://github.com/EddieHubCommunity/LinkFree/pull/2214) )
> 
> These are 3 Customization ideas for the profiles.
> 
> @eddiejaoude Any Suggesstions?

Yes the user providing the background image can cause some displaying issues like the text will not be visible if the user uses a dark background

**Comment by shubhsharma19** [comment] 2023-01-13 15:20
Its better to approach things "simple" first. 

Going for the **"themes"** option instead of **"background image"** is a better option in my opinion. 

Two Basic suggestions are **Dark and Light**. 

Adding theme color ideas 😄
![Theme Ideas for LinkFree](https://user-images.githubusercontent.com/69891912/212354888-85195cea-a32a-4b08-a96a-8dd0d39f9c88.png)

**Comment by KimberlyPangilinan** [comment] 2023-01-13 15:49
> Its better to approach things "simple" first. 
> 
> Going for the **"themes"** option instead of **"background image"** is a better option in my opinion. 
> 
> Two Basic suggestions are **Dark and Light**. 
> 
> What do you think @eddiejaoude ? :)
> 
> Adding theme color ideas Screenshot 😄
> ![Theme Ideas for LinkFree](https://user-images.githubusercontent.com/69891912/212354888-85195cea-a32a-4b08-a96a-8dd0d39f9c88.png)
> 
> 

Or maybe we can add personalization with accent colors.  Accent colors does not affect the display much

I can see here that we have orange as default. We can add some colors like violet and such.

Though it may affect the branding i guess

![Screenshot_20230113_234646_com.android.chrome.jpg](https://user-images.githubusercontent.com/92774426/212360936-ad6d402f-076f-4389-85cd-5eac83d85a1c.jpg)

If we want to preserve the branding as orange, i think let's stick with the light theme and dark theme with the orange as its accent color

**Comment by shubhsharma19** [comment] 2023-01-13 16:12
Great Idea @KimberlyPangilinan, Well, let's see what @eddiejaoude thinks about this. :D

**Comment by eddiejaoude** [comment] 2023-01-14 22:43
Great collaboration everyone 💪 

Yes keeping it simple is a great idea and we can keep improving little by little

**Comment by HarshDeep61034** [comment] 2023-01-15 10:29
yup small steps do make remarkable changes!

**Comment by Siddhesh-Agarwal** [comment] 2023-01-17 04:40
Well, Can I try to make a Dark mode? I am interested to work on this. I found this repo recently (in my starts 😂) and would like to contribute to it.

**Comment by FrozenHearth** [comment] 2023-01-17 17:46
Possible duplicate of #1838 ?
Anyway, dark mode would be a fantastic addition. Was gonna suggest the same.

**Comment by Siddhesh-Agarwal** [comment] 2023-01-17 17:53
on which track are we planning to go:

1) Themes (modes): Dark/Light mode
2) Themes (styles): a user adds a `"style": "dark"` in the `data/<username>.json`  file, then we can apply that style to the user.

**Comment by ManishBisht777** [comment] 2023-01-17 17:56
> on which track are we planning to go:
> 
> 1. Themes (modes): Dark/Light mode
> 2. Themes (styles): a user adds a `"style": "dark"` in the `data/<username>.json`  file, then we can apply that style to the user.

maybe the first one as toggling the dark mode to the whole site would be better than just the profile in my opinion

**Comment by shubhsharma19** [comment] 2023-01-17 18:01
> on which track are we planning to go:
> 
>     1. Themes (modes): Dark/Light mode
> 
>     2. Themes (styles): a user adds a `"style": "dark"` in the `data/<username>.json`  file, then we can apply that style to the user.

I think the first one should be implemented first and see what users actually feel about this.

Or just ask the users by putting a vote or something and let them decide what's better. (Light/Dark or Themes)

**Comment by loftwah** [comment] 2023-01-18 19:23
I like the sound of dark mode

**Comment by shubhsharma19** [comment] 2023-01-19 14:13
Me too @loftwah :D

**Comment by loftwah** [comment] 2023-01-20 04:16
I like when dark mode is triggered by a toggle, say in the top right somewhere. Appwrite does this really well.

**Comment by shubhsharma19** [comment] 2023-01-20 08:02
Looks so good, I Love it!!!! @loftwah

**Comment by k99sharma** [comment] 2023-01-22 19:55
![ezgif com-gif-maker](https://user-images.githubusercontent.com/54969439/213937223-e0b2fae7-4045-4573-a7e7-267b2c0ca006.gif)

I tweaked a little bit with colors in chrome and it looks good!

**Comment by ManishBisht777** [comment] 2023-01-23 04:35
I would like to work on this
starting with a global theme provider

@eddiejaoude we can add to a seperate branch right?

**Comment by ManishBisht777** [comment] 2023-01-27 06:51
> > I would like to work on this
> > starting with a global theme provider
> > @eddiejaoude we can add to a seperate branch right?
> 
> Hey @ManishBisht777 are you working on this? Could you explain what you mean by a global theme provider?

My bad I should have said a bit clearer, There is a package called `next-themes`  it has a wrapper called ThemeProvidor it adds a dark theme support for our website

Not started yet but i am looking if it can be done easily without additional package or not

**Comment by ManishBisht777** [comment] 2023-01-27 06:54
but i think it surely is easy with a package

**Comment by ChinmayMhatre** [comment] 2023-01-27 07:16
> but i think it surely is easy with a package

Looks promising! Else we could always just use the `dark` variant in tailwind

**Comment by ManishBisht777** [comment] 2023-01-27 20:00
Just noticed there is another issue open for the dark theme and someone is assigned to it

**Comment by krshkun** [comment] 2023-02-03 12:57
I can add a small script that can manage permanent state of the dark mode across sessions without any performance gain 👍🏻

This will allow to take user input, if not available go to media queries, if still not available use the default

**Comment by ChinmayMhatre** [comment] 2023-02-15 12:03
Hey @ManishBisht777  not to rush you just wondering if you have starting working on this? Would you mind If I give it a go incase you haven't started yet?

**Comment by ManishBisht777** [comment] 2023-02-15 12:09
> Hey @ManishBisht777 not to rush you just wondering if you have starting working on this? Would you mind If I give it a go incase you haven't started yet?

Ahhhhhhh i forgot about this issue really sorry for that and yes @ChinmayMhatre you can take this let me know if you need any help

**Comment by ChinmayMhatre** [comment] 2023-02-15 12:16
> > Hey @ManishBisht777 not to rush you just wondering if you have starting working on this? Would you mind If I give it a go incase you haven't started yet?
> 
> Ahhhhhhh i forgot about this issue really sorry for that and yes @ChinmayMhatre you can take this let me know if you need any help

Awesome! Yeah I'll let you know if I need help

**Comment by shubhsharma19** [comment] 2023-02-15 12:30
Great! 🎉

**Closed** 2023-04-02 05:20 UTC
Labels: ⭐ goal: addition, 💻 aspect: code, 🟩 priority: low
