### ISSUE TITLE
[BUG] classNames function to be moved back to service folder

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#8562] opened 2023-08-08 08:54 UTC
### Description

I missed this when reviewing a PR that they moved `classNames` file out of the service folder into a new folder at the root, which is messy, we don't need another root folder.

- Move `utils/functions/classNames.js` to `services/utils/classNames.js`
- And update any relevant code

**Comment by Gurnav224** [comment] 2023-08-08 09:03
hey, I want to address this issue 

move  utils/functions/classNames.js  to services/utils/classNames.js

**Comment by dharmik209** [comment] 2023-08-08 16:16
Hey, I want to address this issue can i contribute to this issue?

**Comment by iamabhay17** [comment] 2023-08-08 16:31
hey, i would like to contribute to this issue.

**Comment by SaraJaoude** [comment] 2023-08-08 20:46
This is a duplicate of #8454 so I will close

**Closed by SaraJaoude** 2023-08-08 20:46 UTC
Labels: 🛠 goal: fix, 🤖 aspect: dx, good first issue, 🟧 priority: high, 🔢 points: 2
