### ISSUE TITLE
Inconsistency between filteredUsers and sum of count shown on selected tags

### ISSUE THREAD

**Issue by jenishVadodaria** [EddieHubCommunity/LinkFree#5710] opened 2023-03-29 19:42 UTC
### Description

When selecting a tag for search bar, the filteredUsers does not match the total count shown on the tags.

### Screenshots

![Screenshot (143)](https://user-images.githubusercontent.com/62771159/228649642-77116174-d051-4ca1-a387-5e447e05ef10.png)

**Comment by Deva-1903** [comment] 2023-03-30 14:43
Can I work on this issue?

**Comment by jenishVadodaria** [comment] 2023-03-30 16:36
@eddiejaoude, can you review the issue? I think we need to refactor the filterData function.

**Comment by amandamartin-dev** [comment] 2023-03-30 19:28
Potentially related issue #5470

**Comment by eddiejaoude** [comment] 2023-03-31 03:14
Good spot Amanda 👍 

Thank you for raising @jenishVadodaria but it is a duplicate of #5470 so I will close

**Closed as completed by eddiejaoude** 2023-03-31 03:14 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
