### ISSUE TITLE
[BUG] badge on clear/reset on map overlaps

### ISSUE THREAD

**Issue by ashmeetsmonga** [EddieHubCommunity/LinkFree#8396] opened 2023-07-29 09:49 UTC
### Description

The badge on 'Clear/Reset Filters' button on '/map' page have same background as button when disabled. So it doesn't look good when it overflows over text.

### Screenshots

![Screenshot 2023-07-29 at 3 18 15 PM](https://github.com/EddieHubCommunity/LinkFree/assets/56465357/5fc1bb93-b9e2-4f8c-b34e-c801f3f6c456)

### Additional information

I would like to work on it. Thank You

**Comment by eddiejaoude** [comment] 2023-07-29 13:38
Thank you, but this is a duplicate of another issue https://github.com/EddieHubCommunity/LinkFree/issues/8194 so I will close

note: I have updated the issue title

**Closed by eddiejaoude** 2023-07-29 13:38 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
