### ISSUE TITLE
[FEATURE] Add Project Section

### ISSUE THREAD

**Issue by amitthecoder** [EddieHubCommunity/LinkFree#8264] opened 2023-07-19 15:16 UTC
### Description

Many developers make projects and want to list them in place and share them with other developers and companies for job purposes. If the projects section has been added then other developers and companies can easily access it.

**Comment by eddiejaoude** [comment] 2023-07-20 08:12
Good idea 👍  closing as a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/8224

**Closed by eddiejaoude** 2023-07-20 08:12 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
