### ISSUE TITLE
[FEATURE] Display a message to the user when the link is copied to clipboard

### ISSUE THREAD

**Issue by unnikrishnan2002** [EddieHubCommunity/LinkFree#973] opened 2022-01-12 06:59 UTC
### Description

In the share feature when the user selects to copy the link to clipboard . It should notify the user that the link is copied.

**Comment by unnikrishnan2002** [comment] 2022-01-12 07:01
@avneesh maybe you should have a look at that :eyes:

**Comment by emmalearnscode** [comment] 2022-01-12 08:37
It does in development but there’s an issue with copy to clipboard in production because the site is not on https which stops the copy api from working. It was raised in an issue the other day.

**Comment by emmalearnscode** [comment] 2022-01-12 08:39
I’ll close this as a duplicate of #946

**Closed by emmalearnscode** 2022-01-12 08:39 UTC
Labels: ⭐ goal: addition

**Comment by unnikrishnan2002** [comment] 2022-01-12 08:43
> I’ll close this as a duplicate of #946

Sure
