### ISSUE TITLE
[FEATURE] Better UI on the playground page

### ISSUE THREAD

**Issue by FrozenHearth** [EddieHubCommunity/LinkFree#5337] opened 2023-03-10 17:50 UTC
### Description

1. The playground would look nicer with spacing below the label and the input box.

The form should be moved to components to be reused through the app

2. The profile json field needs an example json in the placeholder or below the input field to guide the user what the format of the profile json should be. 

Pre-filled example is a good idea

3. ~~Lot of white space is there on the page. I think vertically centering the content would look better.~~

4. ~~Better, more user-friendly error message. Is it possible to validate the github username field?~~

The GitHub username field could be validated but we will hit the api rate limit, so suggest we do not do this for now

### Screenshots

![playground](https://user-images.githubusercontent.com/27160715/224387383-12d54c15-1000-4a9c-a932-284a03d991ab.PNG)
![playground12](https://user-images.githubusercontent.com/27160715/224387859-dd950fbe-c91e-42af-82ef-6adc3c63b091.PNG)

**Comment by harshit-002** [comment] 2023-03-11 08:09
@FrozenHearth I would like to work on this, assign it to me, please.

**Comment by FrozenHearth** [comment] 2023-03-11 08:11
Sure, please let one of the maintainers change the status to Ready for Dev. Then you can start working on it.

**Comment by Saikat-Mandal** [comment] 2023-03-12 06:06
Can i work on this issue ?

**Comment by MAYANKpandey14** [comment] 2023-03-12 09:27
> Can i work on this issue ?

For any issue to become  Ready for dev , it has to reviewed by the maintainers and given ready to dev status .
Thank you for your interest in contributing to the community . Once the issue is reviewed , it be assigned . 
@Saikat-Mandal Have a Nice day !!

**Comment by anonymous1508** [comment] 2023-03-15 06:07
how do i  work on this issue ? i m new in open source

**Comment by Saikat-Mandal** [comment] 2023-03-15 08:39
@MAYANKpandey14 yeh got it Mayank.

**Comment by SyedImam1998** [comment] 2023-03-16 15:38
> how do i work on this issue ? i m new in open source , where do i have to work on this issue ? in forked repo or the original one because in forke repo there are no issues visible , i already have made my profile as instructed in doc

Hey @anonymous1508  I would recommend you to go through this video where @eddiejaoude himself explain how to get started in Open Source Contributions [Video](https://www.youtube.com/watch?v=yzeVMecydCE&ab_channel=freeCodeCamp.org)

**Comment by ChinmayMhatre** [comment] 2023-03-17 18:29
> > how do i work on this issue ? i m new in open source , where do i have to work on this issue ? in forked repo or the original one because in forke repo there are no issues visible , i already have made my profile as instructed in doc
> 
> Hey @anonymous1508  I would recommend you to go through this video where @eddiejaoude himself explain how to get started in Open Source Contributions [Video](https://www.youtube.com/watch?v=yzeVMecydCE&ab_channel=freeCodeCamp.org)
> 

Hey @SyedImam1998 , awesome suggestion! Just refrain from tagging folks not related to the issue. It often creates more notifications. Eddie probably already has a mountain of notifications to go through 😂. Hope you understand. Thank you.

**Comment by SyedImam1998** [comment] 2023-03-18 00:45
> > > how do i work on this issue ? i m new in open source , where do i have to work on this issue ? in forked repo or the original one because in forke repo there are no issues visible , i already have made my profile as instructed in doc
> > 
> > 
> > Hey @anonymous1508  I would recommend you to go through this video where @eddiejaoude himself explain how to get started in Open Source Contributions [Video](https://www.youtube.com/watch?v=yzeVMecydCE&ab_channel=freeCodeCamp.org)
> 
> Hey @SyedImam1998 , awesome suggestion! Just refrain from tagging folks not related to the issue. It often creates more notifications. Eddie probably already has a mountain of notifications to go through 😂. Hope you understand. Thank you.

Gotcha updated my text !!!

**Comment by eddiejaoude** [comment] 2023-03-18 01:41
I have edited the issue description and added the label ready for dev. Please re-read and let m know who would like to work on the issue

**Comment by Saikat-Mandal** [comment] 2023-03-18 03:57
@eddiejaoude i would love to work on it !

**Comment by eddiejaoude** [comment] 2023-03-18 04:00
Sure assigned to you @Saikat-Mandal

**Closed** 2023-03-23 03:56 UTC
Labels: ⭐ goal: addition, 💻 aspect: code, 🏁 status: ready for dev, 🔢 points: 3
