### ISSUE TITLE
[BUG] Text not shown in Search For Icon section for dark mode 

### ISSUE THREAD

**Issue by abhijivani3001** [EddieHubCommunity/LinkFree#8502] opened 2023-08-05 06:04 UTC
### Issue
- In the **Search For Icon** section (to add icons for specific link in your profile), while enter icon name in the text box, the text written in it is not shown (**For Dark Mode**).

### Expected Solution
- Font color should be changed to Black or background color of text-box should be black.

## Light Mode
![Screenshot 2023-08-05 112310](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/405dd127-f920-494c-affc-2c7bac51378c)
<br> <hr>

## Dark Mode
![Screenshot 2023-08-05 112337](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/ac138011-7c0d-42e0-95ae-4710d52f4885)
![Screenshot 2023-08-05 113045](https://github.com/EddieHubCommunity/LinkFree/assets/117305467/cb23ef74-2ec7-4d05-a4d8-8ef63ad4fe25)

**Comment by SaraJaoude** [comment] 2023-08-05 13:41
Thank you for raising but this is a duplicate of: https://github.com/EddieHubCommunity/LinkFree/issues/8424 so I will close this.  In future please check what Issues have been raised, to avoid duplication and extra unecessary work for maintainers.

**Closed by SaraJaoude** 2023-08-05 13:41 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
