### ISSUE TITLE
Fix tag totals and popular tags on map page

### ISSUE THREAD

**Issue by lmac-1** [EddieHubCommunity/LinkFree#5470] opened 2023-03-16 02:08 UTC
### Description

At the moment, the popular tags and tag totals on the map page are generated using all LinkFree users. The map page only displays users that have their location set, so the total number for each tags and popular tags should take this into account.

At the moment it isn't so apparent, but when #5405 is fixed, it will be a bit confusing for the user.

### Screenshots

Popular tags and tag totals for the search page (which uses all LinkFree users):

![image](https://user-images.githubusercontent.com/64803272/225491063-cd46db61-6bfa-4e5d-9303-6ac48b52b647.png)

Popular tags and tag totals on the map page should be different to the search page as it is only displaying users with location set:

![image](https://user-images.githubusercontent.com/64803272/225491175-b3074d52-e02d-4049-9f3a-90922c230fd2.png)

**Comment by lmac-1** [comment] 2023-03-22 16:00
@eddiejaoude after seeing your LinkedIn post, could we potentially pair program on this together on Discord once you're all set up in Phuket? I have some ideas on how to solve this but not sure of the "best" way and would be cool to learn from you and the community.

**Comment by eddiejaoude** [comment] 2023-03-23 02:58
Sure sounds good 👍

**Comment by eddiejaoude** [comment] 2023-04-13 05:20
Hey Lucy, as we haven't managed to sync up on this yet with far timezones, we are blocking this issue. So I will unassigned for the moment.

**Comment by lmac-1** [comment] 2023-04-13 16:26
Sorry Eddie this fell off of my radar completely. I did have an idea about how to fix it by passing some query parameters when calling `/api/discover/tags` for the map scenario, and then building some logic around that. Would that be along the right lines for the fix? 

If so, could I have a go at it? I can work on it tomorrow.

**Comment by eddiejaoude** [comment] 2023-04-14 04:06
That might work, maybe something like `/api/discover/tags?location=true` so it only includes tags from people who would be on the map 👍

**Comment by Vishrut19** [comment] 2023-04-17 02:07
Is this issue still open?

**Comment by lmac-1** [comment] 2023-04-17 02:32
Yes @Vishrut19! I actually don't have time right now to work on this, so happy for someone else to pick it up. Eddie or one of the maintainers will need to assign it though.

**Comment by SaraJaoude** [comment] 2023-04-17 02:51
> Is this issue still open?

@Vishrut19 I will assign this to you now

**Comment by Vishrut19** [comment] 2023-04-18 02:29
Hey! Can you please explain this issue in a bit detail?

**Comment by SaraJaoude** [comment] 2023-04-18 04:10
> Hey! Can you please explain this issue in a bit detail?

@Vishrut19 whilst collaboration and asking questions is super important and something we value at EddieHub (we all get stuck at some stage!), one of the things we mention in our Contributing Guide is:

`only request to be assigned an issue if you know how to work on it`

Or if the Issue is unclear then please ask for clarification before you asked for it to be assigned to you. 

Let's see if the community can help you get started with this, but if you are unable to start work on the Issue then we may need to unassign this from you.

**Comment by Vishrut19** [comment] 2023-04-18 05:12
Okay thanks for letting me know @SaraJaoude !

**Comment by eddiejaoude** [comment] 2023-04-18 05:46
I think you can reduce the list before the calculation, to only profiles that contain a location

**Comment by Vishrut19** [comment] 2023-04-18 05:48
Sure I will do it first and then I will ask if I have more queries

**Comment by Vishrut19** [comment] 2023-04-18 07:21
And also to solve this issue! I think I should look in map.js file. Right @eddiejaoude ?

**Comment by amandamartin-dev** [comment] 2023-04-26 21:32
> And also to solve this issue! I think I should look in map.js file. Right @eddiejaoude or @lmac-1?

If you look earlier in the conversation you will see that the method Lucy and Eddie were considering is to manipulate the API logic so taht a query parameter can be passed.  The relevant API  can be found in the project here: ```pages/api/discover```

**Comment by Vishrut19** [comment] 2023-05-06 05:35
Hey! Can someone tell me that is this a bug or what? When I am running the project locally and trying to go to the `Map` section. I can't see any tags.

<img width="1297" alt="Screenshot 2023-05-06 at 11 04 26 AM" src="https://user-images.githubusercontent.com/53470896/236602365-0dbc40e9-a1be-4ae5-aa37-6389844f7627.png">

**Comment by eddiejaoude** [comment] 2023-05-06 05:42
Best to check your terminal and look at the logs for errors - it is probably easier to discuss in EddieHub Discord rather than here

**Comment by Vishrut19** [comment] 2023-05-06 06:05
Sure, I will check it and also if there is some issue I will ping you on EddieHub Discord Server

**Comment by SaraJaoude** [comment] 2023-05-19 04:27
> I would like to take this up.
> 
> Also I would suggest instead of creating `/api/discover/tags?location=true` as mentioned in [#5470 (comment)](https://github.com/EddieHubCommunity/LinkFree/issues/5470#issuecomment-1507897424), we can directly filter the tags in map.js as `data.users` is already having tag details also. We get user, locations and tag details from `/api/users`. There will be no need to call `/api/discover/tags`. This will save us a db hit as well to get the location details in tags.js. Let me know your views on this.

@AJcodes42 thank you for putting your thoughts down.  I can see that you have already been assigned https://github.com/EddieHubCommunity/LinkFree/issues/5945 so at this time we will not be assigning this to you.  

We appreciate your enthusiasm to contribute but please familiarise yourself with the `Working on an Issue (get it assigned to you)` section of the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) and only ask to be assigned 1 Issue at a time.  This will help maintainers with managing the project.

**Comment by AJcodes42** [comment] 2023-05-19 05:19
Sure will take care of this moving forward.

**Comment by AJcodes42** [comment] 2023-05-24 09:42
I would like to work on this issue.

**Comment by SaraJaoude** [comment] 2023-05-26 02:36
> I would like to work on this issue.

@AJcodes42 I have assigned this to you

**Comment by AJcodes42** [comment] 2023-06-01 17:44
Raised pull reqeuest for this issue.

**Closed** 2023-06-07 23:30 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 3
