### ISSUE TITLE
[FEATURE] Sign in Button using github doesnt look good

### ISSUE THREAD

**Issue by ArslanYM** [EddieHubCommunity/LinkFree#6338] opened 2023-04-24 16:32 UTC
### Description

The button is inside a  div which I feel is not necessary.  It can be impoved UI wise

### Screenshots

![1](https://user-images.githubusercontent.com/104521101/234059287-cd3f122e-c967-483e-9f40-402b1ef0cb75.png)

### Additional information

I would love to work on this

**Comment by eddiejaoude** [comment] 2023-04-25 04:53
Thank you for raising but I will close as duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/5856

**Closed by eddiejaoude** 2023-04-25 04:53 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
