### ISSUE TITLE
Tag duplication when case is different on search page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/LinkFree#4676] opened 2023-02-10 18:32 UTC
### Description

On the search page there are 3 different tags for JS due to different use of case.  Recommend standardizing all tags (not just JS) into the same case to prevent duplication

![search bug](https://user-images.githubusercontent.com/97615019/218169864-6f33df1c-e4c3-4952-8737-e94002a39c20.jpg)

**Comment by GauravBurande** [comment] 2023-02-11 11:11
I think there was already the same issue.

**Comment by amandamartin-dev** [comment] 2023-02-11 12:34
> I think there was already the same issue.

I thought so too but when I searched I did not find one.  If you find it, please link it here and then we can close this one.

**Comment by ManishBisht777** [comment] 2023-02-11 16:40
> > I think there was already the same issue.
> 
> I thought so too but when I searched I did not find one. If you find it, please link it here and then we can close this one.

Here #3604

**Comment by ManishBisht777** [comment] 2023-02-11 16:41
but the issue is closed

**Comment by amandamartin-dev** [comment] 2023-02-11 22:12
> but #3604 is closed

Ah Interesting! Perhaps something was changed to make the issue resurface as that ticket was "closed as completed" but it's definitely still happening.  I will leave this open for assessment as it seems to be needed still

**Comment by eddiejaoude** [comment] 2023-02-12 00:26
They all get selected but yes it would be a better UX if they were only displayed once 👍 

<img width="1674" alt="Screenshot 2023-02-12 at 07 25 44" src="https://user-images.githubusercontent.com/624760/218286765-e3c4ac58-1589-4b6d-ab41-37545737eeec.png">

**Comment by joeshajan** [comment] 2023-02-12 04:56
Correct @eddiejaoude It will be a lot better. I would like to fix this issue. Can you assign this to me?

**Comment by eddiejaoude** [comment] 2023-02-12 05:17
Sure, assigned @joeshajan

**Comment by krshkun** [comment] 2023-02-12 07:17
I would suggest we just capitalize/serialize these when the API gives the user profile. That will allow lapps to work with it as well

**Comment by Aadarsh805** [comment] 2023-02-12 16:25
> They all get selected but yes it would be a better UX if they were only displayed once +1
> 
> <img alt="Screenshot 2023-02-12 at 07 25 44" width="1674" src="https://user-images.githubusercontent.com/624760/218286765-e3c4ac58-1589-4b6d-ab41-37545737eeec.png">


I noticed one more thing here, now that we have implemented the functionality where it highlights all the tags ignoring case sensitivity
but there's still this issue, that we can still on some other same tag (but differently spelled) it gets in the search field


https://user-images.githubusercontent.com/95094057/218323391-ac15dd09-66f6-4fe6-acef-0ae01659c330.mp4

I think this will be fixed, once we do the case checking beforehand and then there will be no same tags
that's why didn't raise separate issue for it

**Comment by joeshajan** [comment] 2023-02-12 23:46
> 

Yeah got it will keep that in mind

**Comment by joeshajan** [comment] 2023-02-14 05:51
Can someone please explain how can I get some data in my local database?
Is there any way to data from the production database for testing?

**Comment by Akhilbisht798** [comment] 2023-03-30 05:44
Hey @joeshajan are you still working on this issue?

**Comment by joeshajan** [comment] 2023-03-30 06:04
> Hey @joeshajan are you still working on this issue? if not i would love to contribute to this.

I have already raised a pr

**Comment by eddiejaoude** [comment] 2023-03-30 06:06
> Hey @joeshajan are you still working on this issue? if not i would love to contribute to this.

@Akhilbisht798 please see the issue timeline above your comment, it shows the linked PRs as well as the conversation

**Comment by Akhilbisht798** [comment] 2023-03-30 06:10
Oh my bad, i misunderstood it. I am really sorry about it.

**Comment by amandamartin-dev** [comment] 2023-04-26 21:36
Hello @joe-shajan I see you mentioned raising a PR, but this issue still exists on production.  Are you working on this still or can it be reassigned? If a PR is open, can you link it - I am not seeing it

**Comment by shobhitexe** [comment] 2023-05-08 04:02
Hey is anyone working on it 
was waiting for linkfree to migrated to atlas as eddie said but i see the problem is still there
https://github.com/EddieHubCommunity/LinkFree/issues/6612#event-9168957682
am from the above issue 
i see its assigned to someone but he is not working on it 
i would like to take this if no ones working on it 
Thanks

**Comment by SaraJaoude** [comment] 2023-05-29 01:28
Due to lack of activity I have unassigned this issue. 

@shobhitexe given your comments on [here](https://github.com/EddieHubCommunity/LinkFree/pull/5534#discussion_r1203612643) would you like me to assign this issue to you?

**Comment by shobhitexe** [comment] 2023-05-29 04:00
> Due to lack of activity I have unassigned this issue.
> 
> @shobhitexe given your comments on [here](https://github.com/EddieHubCommunity/LinkFree/pull/5534#discussion_r1203612643) would you like me to assign this issue to you?

Sure i would love to work on this

**Comment by SaraJaoude** [comment] 2023-05-29 04:30
> > Due to lack of activity I have unassigned this issue.
> > @shobhitexe given your comments on [here](https://github.com/EddieHubCommunity/LinkFree/pull/5534#discussion_r1203612643) would you like me to assign this issue to you?
> 
> Sure i would love to work on this

@shobhitexe I have assigned this to you

**Closed** 2023-05-31 02:10 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 3
