### ISSUE TITLE
[Quickstart: filename capitalisation not clear] 

### ISSUE THREAD

**Issue by GrahamTheDevRel** [EddieHubCommunity/LinkFree#6911] opened 2023-05-16 08:23 UTC
## Problem
While following the quick start I did not register what "your GitHub username exactly as it appears" meant in point 7 (https://linkfree.io/docs/quickstart).

This resulted in extra work on both sides for no reason.

## Solution
This would be much better if it showed an example of doing it correctly vs incorrectly.

**I suggest something like the following:**

---
7. In the file path at the top, add `data/` then with your GitHub username, exactly as it appears **including capitalisation**, and append .json.

For example for username **"SaraJaoude"**:

✅ LinkFree/data/SaraJaoude.json (including capitalisation in filename)
❌ LinkFree/data/sarajaoude.json (filename capitalisation does not match username capitalisation)

**Note:** If your GitHub username is all lower case the file name should also be lower case.

---

## Reasoning
This added extra work on both sides for no reason. 

Additionally many beginners may get stuck with renaming a file as Git is case insensitive so it will not register a file name change without switching off case insensitivity or using `--force` on a `mv` command.

**This could be a good first issue for someone**

**Comment by eddiejaoude** [comment] 2023-05-16 12:10
Thanks Graham for the great suggestion 👍  the issue is now `ready for dev`, would you like me to assign the issue to you?

**Comment by SaraJaoude** [comment] 2023-05-16 13:04
Great! It would be good if the example of what to do/what not to do is in the same style as our examples in the Style Guide (i.e. `recommended/not recommended`): https://linkfree.io/docs/docs-style-guide

**Comment by zaidahmad25** [comment] 2023-05-16 13:20
Can i work on this issue?

**Comment by Keshav-0907** [comment] 2023-05-16 18:48
Can I work on this task? @eddiejaoude

**Comment by SaraJaoude** [comment] 2023-05-17 00:59
@zaidahmad25 I will assign this to you. Please see above message regarding keeping to the Style Guide.

**Comment by zaidahmad25** [comment] 2023-05-17 06:07
Thank you very much @SaraJaoude 

Sure, I'll keep in mind the Style Guide. 

Also, thank you @GrahamTheDevRel for being so considerate 😃

**Closed** 2023-05-18 03:19 UTC
Labels: 🏁 status: ready for dev, 🤖 aspect: dx, good first issue, 🔢 points: 1, 📄 aspect: text
