### ISSUE TITLE
Card Grows Out of Screen on Hover on Event Page

### ISSUE THREAD

**Issue by ramanand-rv** [EddieHubCommunity/LinkFree#5584] opened 2023-03-21 10:33 UTC
### Description

When hovering over an event card on the event page, the card expands beyond the boundaries of the screen, making the content touch the boundaries of the screen. The card over grows in size horizontally. This issue occurs consistently on web browsers in desktop view only. It's absolutely fine in Mobile view.

### Screenshots

Without Hover:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80584888/226579675-6fbea33f-133a-4e14-bc87-84bdff89ce58.png">

When Hovered:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80584888/226579875-8c1c72a3-ecbf-4e12-8d01-067164596d6e.png">

**Comment by karthiknadar1204** [comment] 2023-03-22 15:54
I would like to work on this issue,could you please assign to me

**Comment by harshit-002** [comment] 2023-03-22 18:36
Can I work on this issue?

**Comment by eddiejaoude** [comment] 2023-03-23 03:49
Please do not request to be assigned an issue if it is not in `status: ready for dev` it creates more notifications for maintainers and it will not be assigned

**Comment by eddiejaoude** [comment] 2023-03-23 03:49
the issue is now `ready for dev`, who would like the issue?

**Comment by Saikat-Mandal** [comment] 2023-03-23 03:50
yeh sure i would love to work on it !

**Comment by eddiejaoude** [comment] 2023-03-23 03:55
Sure @Saikat-Mandal , assigned

**Comment by sanyamx** [comment] 2023-03-23 08:23
Hey! I would like to work on this can you please assign it to me? Thank You!

**Comment by harshit-002** [comment] 2023-03-23 13:33
> Hey! I would like to work on this can you please assign it to me? Thank You!

It is already assigned to someone else.

**Comment by Palakkgoyal** [comment] 2023-03-28 07:55
Is anyone still working or I can give a try?

**Comment by Saikat-Mandal** [comment] 2023-03-28 09:29
@Palakkgoyal actually i am working on it  , I had bit hurry schedule due to my ongoing college exams.

**Comment by Palakkgoyal** [comment] 2023-03-28 12:48
Oh okay, no worries @Saikat-Mandal

**Comment by Saikat-Mandal** [comment] 2023-03-29 03:38
@Palakkgoyal you can give it a try if you want... i don't think so i would able start before 1st april

**Comment by khanahmar** [comment] 2023-03-29 19:30
is this issue still here

**Comment by eddiejaoude** [comment] 2023-03-30 03:57
I think this issue has now be fixed and the PR was merge (but did not referenced the issue)

**Closed by eddiejaoude** 2023-03-30 03:57 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, good first issue, 🔢 points: 1
