### ISSUE TITLE
Delay in loading Search Tab when clicking it 

### ISSUE THREAD

**Issue by geeky-sambhav** [EddieHubCommunity/LinkFree#6100] opened 2023-04-15 11:27 UTC
### Description

When I click on search tab it takes about 2-3 seconds to load as compared to other tabs such as Events, Docs, Playground which load up instantly

### Screenshots

https://www.loom.com/share/2b3a8b53bd034169a81a6eba3317441a

### Additional information

I have shared the recording above for your reference

**Comment by pratham-yuxo** [comment] 2023-04-15 12:50
I have also noticed this delay. What can be the reason?

**Comment by iamvbenz49** [comment] 2023-04-15 12:56
@eddiejaoude i think I scan fix this with right mentorship and help

**Comment by ManishBisht777** [comment] 2023-04-15 13:42
Thats because during the page load if loads all the profiles present in the `/data` folder, but we can take a different path by showing a loader or transition b/w  pages to make the delay look less and also provide  a good UX

**Comment by iamvbenz49** [comment] 2023-04-15 14:08
> Thats because during the page load if loads all the profiles present in the `/data` folder, but we can take a different path by showing a loader or transition b/w pages to make the delay look less and also provide a good UX

so can't we make it load like other tabs?

**Comment by priyankarpal** [comment] 2023-04-15 14:31
This issue is duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/2815

**Comment by eddiejaoude** [comment] 2023-04-15 14:55
Great collaboration, but I will close as @priyankarpal correctly notices it is a duplicate, multiple conversations are difficult to track

**Closed by eddiejaoude** 2023-04-15 14:55 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
