### ISSUE TITLE
[FEATURE] Add dark & Light mode 

### ISSUE THREAD

**Issue by priyankarpal** [EddieHubCommunity/LinkFree#4900] opened 2023-02-17 08:35 UTC
### New idea
* add a toggle switch for dark & light mode

what do you think?

**Comment by swagataroy30** [comment] 2023-02-17 08:47
This issue seems to be a duplicate of #2957

**Comment by schmelto** [comment] 2023-02-17 09:35
#2957 is tackling this issue already. Feel free to leave your comments there. :)

**Closed by schmelto** 2023-02-17 09:35 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
