### ISSUE TITLE
[FEATURE] Customisable Profile Themes

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/LinkFree#616] opened 2021-10-28 18:37 UTC
### Description

In light of the changes made in #513, I think it would be really great if this gradient config is an "optional" enhancement that people could use in their profiles. An option in the data config files for a hex code or a "trigger" string, which defines the background for the page would be really great. Maybe we can call it **"theme"**

`/public/data/<file>.json`
```
{
  "name": "J. Doe",
  "bio": "Lorem Ipsum",
  "avatar": "https://github.com/<name>.png",
  "theme": "gradient", // or "0xffff00" or "0xfc0bb8" or "default"
  "links": [
    {
      "name": "Follow me on GitHub",
      "url": "https://github.com/<name>",
      "icon": "github"
    },
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/<name>",
      "icon": "twitter"
    }
  ]
}
```

### Additional information

Stems from #513 and this is a feature that linktree and other projects also include.

**Comment by Tejas-Teju** [comment] 2021-11-23 19:39
@Vyvy-vi @Panquesito7 
I am new to open source, can I work on this?

**Comment by Panquesito7** [comment] 2021-11-23 19:46
> @Vyvy-vi @Panquesito7 I am new to open source, can I work on this?

@Vyvy-vi, will you still work on this? 😅

**Comment by Vyvy-vi** [comment] 2021-11-24 00:17
If you want to, go ahead! :)

**Comment by Tejas-Teju** [comment] 2021-11-24 17:42
Should we add a button called theme and select the color or gradient from color picker? and then save the value to the .json file?

**Comment by krishguptadev** [comment] 2021-11-25 03:03
> Should we add a button called theme and select the color or gradient from color picker? and then save the value to the .json file?

that will be weird to integrate 😅 I think we can allow the user to add a gradient in the JSON directly...

**Comment by Vyvy-vi** [comment] 2021-11-26 13:40
yes, I think for colours, we can have some default color text values(like 'red', 'blue', etc etc. or maybe 'classic', 'modern', 'xyz' and if those aren't present, it uses colour hashes)

**Comment by krishguptadev** [comment] 2021-11-26 13:44
> yes, I think for colours, we can have some default color text values(like 'red', 'blue', etc etc. or maybe 'classic', 'modern', 'xyz' and if those aren't present, it uses colour hashes)

looks cool, a gradient could be a linear-gradient property... opening support for custom hex codes as well

**Comment by Vyvy-vi** [comment] 2021-11-28 19:26
> looks cool, a gradient could be a linear-gradient property... opening support for custom hex codes as well

That can be neat!
There's so much room to customise in here, once an MVP version of this is created.

**Comment by Tejas-Teju** [comment] 2021-11-29 01:52
Can anyone help me understand it a bit more? any other platform to discuss more on this than GitHub?

**Comment by krishguptadev** [comment] 2021-11-29 02:54
> Can anyone help me understand it a bit more? any other platform to discuss more on this than GitHub?

Discord?

**Comment by krishguptadev** [comment] 2021-11-29 02:55
> > looks cool, a gradient could be a linear-gradient property... opening support for custom hex codes as well
> 
> That can be neat! There's so much room to customise in here, once an MVP version of this is created.

so it would be `styles={{ background: profile.background ?? '#fff' }}` I believe.

**Comment by Vyvy-vi** [comment] 2021-11-29 10:59
> Can anyone help me understand it a bit more? any other platform to discuss more on this than GitHub?

I think it makes sense to discuss this in the issue itself so that we can maintain the context.
But certainly, feel free to ask any questions on our discord server - http://discord.eddiehub.org/

**Comment by Tejas-Teju** [comment] 2021-12-14 07:48
I am following below to customize the background, please let me know the right method:
1. In public/data/<file>.json file I am assuming there is a key called "theme" where the users will add background-color 
**Note**: At present there is no key called "theme" in the JSON files, but in case if it is present then add the customized theme else add default value i.e. White.
2. Background should remain White in the Home.js page but when the user navigates to their respective ProfilePage.js then the background theme should apply

I tried 2 methods:
1. Apply the background to the body using document object but the issue is it applies to the Home page as well

**ProfilePage.js** 
![image](https://user-images.githubusercontent.com/34937107/145952927-c4857c09-6d6d-4598-b959-7dcb867c528f.png)

2. Create a **div** tag and add background to it but it doesn't cover the whole body. This just wraps Profile and Link components but I am not sure how to apply this theme to the body for individual users I need help on this.

**ProfilePage.js**
![image](https://user-images.githubusercontent.com/34937107/145954220-34cba104-3772-4193-9007-fdd215cf65a0.png)
![image](https://user-images.githubusercontent.com/34937107/145954496-aa482ffc-588a-4f3a-9d08-3ea1763fe125.png)

**Comment by Vyvy-vi** [comment] 2021-12-16 15:16
I think you'd want to modify the https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/UserProfile/User.js file

**Comment by Tejas-Teju** [comment] 2021-12-16 17:20
@Vyvy-vi, I made changes and created a PR-[820](https://github.com/EddieHubCommunity/LinkFree/pull/820) please review it.

**Comment by eddiejaoude** [comment] 2022-11-05 22:57
A new version of LinkFree got released. We have a lot more flexibility now

I will close this and a new issue can be created

**Closed by eddiejaoude** 2022-11-05 22:57 UTC
Labels: ⭐ goal: addition, 🕹 aspect: interface, 💬 talk: discussion, no-issue-activity
