### ISSUE TITLE
[BUG] Outline on milestone edit button

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/LinkFree#8188] opened 2023-07-14 12:45 UTC
### Description

There is a bit of an outline of the first three edit buttons on the milestones page for me.

### Screenshots

![whiteline](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/c575dfad-3f32-4902-bda4-8f9158e13c64)
![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/d72df820-87dc-42fe-8755-b65b42760191)

### Additional information

It only happens to the first three of them.

**Comment by ChinmayMhatre** [comment] 2023-07-15 11:18
![image](https://github.com/EddieHubCommunity/LinkFree/assets/51131670/2c9952a0-2a23-4e47-8647-3341c4d3b554)
Occurs in mine as well

**Comment by amandamartin-dev** [comment] 2023-07-16 13:51
I think it's because it's overlapping the icon and what you are seeing is a bit of the icon peeking out.

**Comment by eddiejaoude** [comment] 2023-07-16 19:42
yep that is correct, the edit button is over the top 

I am going to close this as I think it is a duplicate of https://github.com/EddieHubCommunity/LinkFree/issues/7844

**Closed by eddiejaoude** 2023-07-16 19:42 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
