### ISSUE TITLE
Hover issue in the nav bar links

### ISSUE THREAD

**Issue by YOKESHCR** [EddieHubCommunity/LinkFree#6296] opened 2023-04-22 18:40 UTC
### Description

When the links are hovered on I am able to get the desired action which you want to perform which is changing the background color and the text color and giving it a border color to the link.
But when I switch over to hovering another link I am able to see the previously hovered link underlined as mentioned in the 1st screenshot.
This appears for a brief time and suddenly vanishes.
This happens to every link. Is this the desired functionality which you wanted the link to do or is this a bug. To me it looks like a bug

### Screenshots

![image](https://user-images.githubusercontent.com/27686539/233801068-2a74b92b-7acc-4ebb-84be-50cfabf7d19a.png)

**Comment by eddiejaoude** [comment] 2023-04-25 04:44
Can you record a video as I am not sure understand how to replicate it - I will unlock the issue for further discussion

**Comment by amandamartin-dev** [comment] 2023-04-26 20:48
> Can you record a video as I am not sure understand how to replicate it - I will unlock the issue for further discussion

Tested - unable to replicate (chrome/mac/dark and light mode). Hopefully the video will help.

To test hover over links in the nav bar passing from one to the next.  What this person is seeing is a brief underline that remains even once the element is no longer in focus.

**Comment by eddiejaoude** [comment] 2023-04-27 13:32
Thank you for replicating, but can you explain how you managed to replicate it please?

**Comment by YOKESHCR** [comment] 2023-04-27 13:41
@eddiejaoude I just hovered on a link paused for a second or two..Then hovered on to the other and continued the same.

You can also refer to the below attached screen recording
 

https://user-images.githubusercontent.com/27686539/234880194-6e39f5ca-8274-49a5-9aa2-269fb3baac75.mp4

**Comment by eddiejaoude** [comment] 2023-04-27 13:56
thank you for the video, I still can't replicate it. I think the operating system and browser and browser version needs to be shared - it might only be a small group effected and not worth trying to over engineer a solution that the browser will fix soon

**Comment by amandamartin-dev** [comment] 2023-05-01 08:59
I tried replicating this with throttling for CPU and network and am also unable to replicate the issue. I agree with Eddie that it's not clear enough exactly under what conditions this is happening or how widespread the issue is.  I would vote to not work on this at this time as it is not blocking the UX/functionality and is unable to be clearly defined.

**Comment by eddiejaoude** [comment] 2023-05-01 17:06
Thank you @amandamartin-dev for testing and clarifying 👍 

Thank you @YOKESHCR for raising this issue, but I will close this issue for now

**Closed by eddiejaoude** 2023-05-01 17:06 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix, 💬 talk: discussion
