### ISSUE TITLE
[FEATURE] New styles for profile section header

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2171] opened 2022-11-07 12:11 UTC
### Description

we can change the profile section from 
##this
![image](https://user-images.githubusercontent.com/89926834/200306857-ac97f273-4cf2-49f5-ad1f-02b90936b7ea.png)

## to this
![image](https://user-images.githubusercontent.com/89926834/200306959-448dc154-bf9e-4ac8-8d76-d6f5a6a959a8.png)

hence making it more promising in continuity with #2141

**Comment by ManishBisht777** [comment] 2022-11-07 12:12
This issue can be divided into 2 parts

1) making ui for the page (working on)
2) integrating and making it dynamic

**Comment by ManishBisht777** [comment] 2022-11-07 16:22
![image](https://user-images.githubusercontent.com/89926834/200361440-5724298a-768a-49fe-862f-e67fc622c3a4.png)

**Comment by ManishBisht777** [comment] 2022-11-07 16:24
![image](https://user-images.githubusercontent.com/89926834/200361679-468e2be0-dfd9-4aab-9cf2-abe295e711fe.png)

**Comment by eddiejaoude** [comment] 2022-11-08 17:09
If the issue is being split up in to smaller issues, please close this issue to avoid confusion and PRs can be created for each smaller issue

**Comment by ManishBisht777** [comment] 2022-11-08 17:15
I have created a pull request for this, I am closing #2141

**Comment by ManishBisht777** [comment] 2022-11-08 17:16
I have created a pull request for this, I am closing #2141 as the issue is been split up into #2171, #2182 and one more issue that is not created yet

**Comment by SaraJaoude** [comment] 2023-02-03 13:52
Let's stick with the current design as this comes with Tailwind components we purchased and we can revisit this in the future.

**Closed by SaraJaoude** 2023-02-03 13:52 UTC
Labels: ⭐ goal: addition
