### ISSUE TITLE
[DOCS] <Typo mistake in the Environment variables documentation>

### ISSUE THREAD

**Issue by amanpreet-dev** [EddieHubCommunity/LinkFree#7986] opened 2023-07-05 12:47 UTC
### Description

There is a typo mistake in the environment variables documentation.

The description of `NEXTAUTH_URL` variable is 

> The url you visit for the app, loaclhost:3000 or Gitpod url

It should be 

> The url you visit for the app, localhost:3000 or Gitpod url

### Screenshots

<img width="1665" alt="Screenshot 2023-07-05 at 6 15 09 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/57353834/642cd3b2-2811-4fa0-8a57-433eddd1c3fa">

### Additional information

Please assign this issue to me. Happy to resolve this.

**Comment by AlimurtuzaCodes** [comment] 2023-07-07 06:57
I can fix this issue assign it to me.

**Comment by SaraJaoude** [comment] 2023-07-07 06:57
@amanpreet-dev good spot. In future it would be even more helpful to annotate the screenshot to show where the mistake is.  

Unfortunately I cannot assign this to you, as you previously requested another issue to be assigned - in accordance with our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per person.

**Comment by amanpreet-dev** [comment] 2023-07-07 07:03
> @amanpreet-dev good spot. In future it would be even more helpful to annotate the screenshot to show where the mistake is.
> 
> Unfortunately I cannot assign this to you, as you previously requested another issue to be assigned - in accordance with our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per person.

Understood 👍

**Comment by JijoJames04** [comment] 2023-07-07 11:11
Hey, I am new to open source and I wish to learn and contribute to open source. If this is any kind of small fix can I try?

**Comment by bhavya2021245** [comment] 2023-07-07 18:52
I can fix this issue can you please assign it to me

**Comment by Viveksati5143** [comment] 2023-07-07 19:51
> @amanpreet-dev good spot. In future it would be even more helpful to annotate the screenshot to show where the mistake is.
> 
> Unfortunately I cannot assign this to you, as you previously requested another issue to be assigned - in accordance with our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) we only assign one issue per person.

May I work in this issue?

**Comment by SaraJaoude** [comment] 2023-07-08 06:33
> Hey, I am new to open source and I wish to learn and contribute to open source. If this is any kind of small fix can I try?

@JijoJames04 this issue has the label `good first issue` which means it is good for those starting out. Here is our [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) - please read through this to familiarise yourself with the project.  In particular you will see that we ask:

 - if an Issue is unclear, ask questions to get more clarity before asking to have the Issue assigned to you
 - only request to be assigned an Issue if you know how to work on it
 
 If you still wish to be assigned the issue and as you were the first to request this then please let the maintainers know.  You can ask any questions and collaborate in the[ EddieHub Discord](https://discord.com/invite/jZQs6Wu) but we do ask that you only request this Issue to be assigned to you if you have a good idea as to how to work on it.

**Comment by SagarBawanthade** [comment] 2023-07-08 07:53
Please assign this issue to me .

**Comment by akkshitgupta** [comment] 2023-07-08 08:18
As the issue is `good first issue` i hope this should be assigned to a new contributor as you said above. I've read contributing guide as well and knows the issue clearly.

please assign to me if possible.

**Comment by SaraJaoude** [comment] 2023-07-09 08:33
> I can fix this issue can you please assign it to me

@bhavya2021245 as I have not heard from @JijoJames04 I have assigned this to you.

**Comment by bhavya2021245** [comment] 2023-07-09 08:43
Thankyou I will just fix it ..

**Closed** 2023-07-09 10:17 UTC
Labels: 🏁 status: ready for dev, good first issue, 📄 aspect: text
